<!-- primero stores siempre -->
<script type="text/javascript" src="<?=$this->basePath();?>/js/stores/factEgresoStore.js"></script>
<script type="text/javascript" src="<?=$this->basePath();?>/js/stores/stockEstadoFacturaStore.js"></script>
<script type="text/javascript">
function hideBloque()
{
	var cajaMensaje = Ext.getCmp('messageBox');
	if(cajaMensaje){
		cajaMensaje.addClass('oculto');
	}	
}

var mainStore = factEgresoStore;

viewContainer.bodyPanel = [{
	layout: 'fit',
	xtype: 'container',
	autoHeight: true,
	cls: 'fittedContainer',
	items: [
			{
				xtype: 'container',
				autoHeight: true,
				id: 'secondMainContainer',
				layout: 'column',
				items:[
						{
							xtype: 'container',
							columnWidth: .65,
							layout: 'anchor',
							items:[
									{
										xtype: 'container',
										html: 'Mantener Egresos',
										cls: 'mainTitle'
									},
									{
				       	       			xtype: 'container',
				       	       			itemId: 'gridContainer',
				       	       			cls: 'gridContainer',
				       	       			layout: 'anchor',
				       	       			items: [
				       	       			        {
					       	       			        xtype: 'toolbar',
					       	       			        style:{padding:'5px'},
					       	       			        items:[
					       	       			               {
						       	       			               xtype: 'displayfield',
						       	       			               style:{margin: '0 5px'},
						       	       			         	   value: 'Nro.: '
					       	       			               },
					       	       			               {
						       	       			               xtype: 'textfield',
						       	       			               name: 'doc_nro',
						       	       			               width: 75
					       	       			               },
					       	       			               {
						       	       			               xtype: 'displayfield',
						       	       			               style:{margin: '0 5px'},
						       	       			         	   value: 'Fecha Desde: '
					       	       			               },
					       	       			               {
						       	       			               xtype: 'datefield',
						       	       			               name: 'doc_fecha_desde',
						       	       			               width: 75
					       	       			               },
					       	       			               {
						       	       			               xtype: 'displayfield',
						       	       			               style:{margin: '0 5px'},
						       	       			         	   value: 'Fecha Hasta: '
					       	       			               },
					       	       			               {
						       	       			               xtype: 'datefield',
						       	       			               name: 'doc_fecha_hasta',
						       	       			               width: 75
					       	       			               },
					       	       			               {
						       	       			               xtype: 'displayfield',
						       	       			               style:{margin: '0 5px'},
						       	       			         	   value: 'Estado: '
					       	       			               },
					       	       			               {
			       												fieldLabel: 'Estado',
			       												hiddenName: 'doc_tipo',
			       												width: 75,
			       												forceSelection: true,
			       												valueField: 'id',
			       												displayField:'valor',
			       												xtype: 'combo',
			       												store: stockEstadoFacturaStore,
			       												typeAhead:true,
			       												mode:'local'
		       												},
					       	       			                '->',
					       	       			         		{
						       	       			               xtype: 'button',
						       	       			         	   iconCls: 'addIcon',
						       	       			               text: 'Buscar',
						       	       			               handler: function(b,e){
																    var padre = b.ownerCt;
																    //obtener valor del campo de texto
																    var campo = padre.find('name','doc_nro');
																    
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    mainStore.setBaseParam('s[doc_nro]',campo.getValue());
																    }
																    
																    campo = padre.find('hiddenName','doc_tipo');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    mainStore.setBaseParam('s[doc_tipo]',campo.getValue());
																    }
																    
																    campo = padre.find('name','doc_fecha_desde');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    mainStore.setBaseParam('s[doc_fecha_desde]',campo.getValue());
																    }
																    
																    campo = padre.find('name','doc_fecha_hasta');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    mainStore.setBaseParam('s[doc_fecha_hasta]',campo.getValue());
																    }
																    
																    mainStore.load();
								       	       			       }
					       	       			               },
					       	       			         		{
						       	       			               xtype: 'button',
						       	       			         	   iconCls: 'addIcon',
						       	       			               text: 'Limpiar',
						       	       			               handler: function(b,e){
																    var padre = b.ownerCt;
																    //obtener valor del campo de texto
																    var campo = padre.find('name','doc_nro');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    campo.setValue(null);
																	    mainStore.setBaseParam('s[doc_nro]',null);
																	    
																    }
																    
																    
																    campo = padre.find('hiddenName','doc_tipo');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    campo.setValue(null);
																	    mainStore.setBaseParam('s[doc_tipo]',null);
																	    
																    }
																    
																    
																    campo = padre.find('name','doc_fecha_desde');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    campo.setValue(null);
																	    mainStore.setBaseParam('s[doc_fecha_desde]',null);
																	    
																    }
																    
																     campo = padre.find('name','doc_fecha_hasta');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    campo.setValue(null);
																	    mainStore.setBaseParam('s[doc_fecha_hasta]',null);
																	    
																    }
																    
																    mainStore.load();
								       	       			       }
					       	       			               }
							       	       			]
				       	       			        },
				       	       					{
				               						xtype: 'grid',
				               						height: 300,
				               						id: 'mainGrid',
				               						stripeRows: true,
				               						loadMask: true,
				               						sm: new Ext.grid.CellSelectionModel(),
				               						viewConfig: {
				               					        forceFit: true,
				               					        emptyText: 'Sin Registros',
				               					        loadingText: 'Cargando .. '
				               						},
				               						store: mainStore,
				               						cm: new Ext.grid.ColumnModel([
														{ header: "Nro.", dataIndex: 'doc_nro', width: 120},
														{ header: "Fecha", dataIndex: 'doc_fecha',  width: 150},
														{ header: "Estado", dataIndex: 'estado',  width: 65, renderer:function(v,meta,record){
															if(v == 'P')
																return 'Pagado';
															else if(v == 'A')
																return 'Anulado';
															else return v;
														}},
														{ header: "Tipo", dataIndex: 'doc_tipo',  width: 150, renderer:function(v,meta,record){
															if(v == 'F')
																return 'Factura';
															else if(v == 'T')
																return 'Traslado';
															else if(v == 'R')
																return 'Remisi&oacute;n';
															else return v;
														}},
														{ header: "Total", dataIndex: 'total_egreso',  width: 65},
														{ header: "Moneda", dataIndex: 'moneda_simbolo',  width: 65},
														{ header: "Ver", dataIndex: null,  width: 32, align: 'center', renderer: function(v,meta,record){
															return '<div class="viewIcon" onclick="verMoneda(' + record.data.cont_moneda_id + ')"></div>';
														}},
														{ header: "Editar", dataIndex: null,  width: 32, align: 'center', renderer: function(v,meta,record){
															return '<div class="editIcon" onclick="editarMoneda(' + record.data.cont_moneda_id + ')"></div>';
														}}
														])
				           						}
				       	       			]
				       	   			},
				       	   			{
				       	       			xtype: 'toolbar',
				       	       			layout: 'toolbar',
				       	       			cls: 'pagingContainer',
				       	       			items:[
						       	       			'->',
				       	       	   				{
				       	       	       				xtype: 'paging',
				       	       	       				displayInfo: true,
				       	       	       				store: mainStore,
				       	       	       				pageSize: 10,
				       	       	       				preprendButtons: true
				       	       	   				}
				       	       			]
				       	   			}
							]
						},
						{
							xtype: 'container',
							columnWidth: .35,
							layout: 'anchor',
							items:[
			    					{
			    						xtype: 'container',
			    						layout: 'anchor',
			    						cls: 'oculto',
			    						id: 'messageBox',
			    						items:[
			    						       {
			        						       xtype: 'container',
			    						    	   html: 'Generico'
			    						       }
			    					
			   	    					]
			    					},
							       {
									     xtype: 'container',
									     layout: 'anchor',
									     id: 'formContainer'
							       }
									/*{
										xtype: 'panel',
										title: 'Crear Org',
										cls: 'ladoDerecho',
										layout: 'anchor',
										height: 200,
										items:[]
									}*/
							]
						}
				]
			}
	]
},
{
	xtype: 'container',
	columnWidth: 1,
	layout: 'column',
	cls: 'quickAccessBottom',
	items:[
			{
				cls: 'dataBottom',
				html: 'Agregar Organizacion',
				xtype: 'container'
			},
			{
				cls: 'dataBottom',
				html: 'Agregar Otra Cosa',
				xtype: 'container'
			},
			{
				cls: 'dataBottom',
				html: 'Ir Para Otro Lado',
				xtype: 'container'
			}				
	]
}];
</script>