<!-- primero stores siempre -->
<script type="text/javascript" src="<?=$this->basePath();?>/js/stores/genericoProductoStore.js"></script>
<script type="text/javascript" src="<?=$this->basePath();?>/js/stores/contMonedaStore.js"></script>
<!-- despues lo demas -->
<script type="text/javascript" src="<?=$this->basePath();?>/js/forms/stockArticulo.js"></script>
<script type="text/javascript" src="<?=$this->basePath();?>/js/common/hideBloque.js"></script>
<script type="text/javascript">

function verArticulo(id)
{
	
	//var registro = mainStore.getById(id);
	
	//if(registro)
	//{
		var destino = Ext.getCmp('formContainer');
		if(destino)
		{
			destino.removeAll();
			//hacemos solicitud

			Ajax.PostElement.request({
				url: baseURL + '/stock/articulo/get',
				success: function(response, opt){
					//mainStore.reload();
					var data = Ext.decode(response.responseText);
					var addedEl = destino.add(formularioStockArticulo(false, data, true, false));
					destino.doLayout();
					addedEl.body.highlight();
				},
				params:{id:id}
			});		
				
			
		}
	//}
}

function editarArticulo(id)
{
	
	//var registro = mainStore.getById(id);
	
	//if(registro)
	//{
		var destino = Ext.getCmp('formContainer');
		if(destino)
		{
			destino.removeAll();
			//hacemos solicitud

			Ajax.PostElement.request({
				url: baseURL + '/stock/articulo/get',
				success: function(response, opt){
					//mainStore.reload();
					var data = Ext.decode(response.responseText);
					var addedEl = destino.add(formularioStockArticulo(false, data, false, false));
					destino.doLayout();
					addedEl.body.highlight();
				},
				params:{id:id}
			});		
				
			
		}
	//}
}

function borrarArticulo(id)
{

	console.log(id);	
	var registro = mainStore.getById(id);
	
	if(registro)
	{
		var destino = Ext.getCmp('formContainer');
		if(destino)
		{
			destino.removeAll();
			//hacemos solicitud

			Ext.Msg.confirm('Eliminar','Desea eliminar el elemento ' + registro.data.nombre, function(a,b){
				if(a == 'yes')
				{
					Ajax.PostElement.request({
						url: baseURL + '/stock/articulo/delete',
						success: function(response, opt){
							mainStore.reload();
						},
						jsonData:{delete:{stock_articulo_id : id}}
					});	
				}
			});
			
		}
	}
}

var mainStore = new Ext.data.JsonStore({
	// store configs
	totalProperty: 'numResults',
	url: baseURL + '/stock/articulo/index',
	// reader configs
	root: 'records',
	paramNames: {
		start: 'p[page]',
		limit: 'p[limit]'
	},
	baseParams: {
		'p[limit]': 10,
		'p[page]': 0
	},
	autoLoad:true,
	idProperty: 'stock_articulo_id',
	fields: ['stock_articulo_id','categoria','codigo','existencia','marca','nombre','precio_venta','moneda','simbolo']
});

var stockCategoriaStore = new Ext.data.JsonStore({
	// store configs
	url: baseURL + '/stock/combos/categoria',
	// reader configs
	autoLoad:true,
	root: 'records',
	baseParams: {
		'p[limit]': 'all'
	},
	idProperty: 'stock_categoria_id',
	fields: ['stock_categoria_id','categoria']
});

var stockMarcaStore = new Ext.data.JsonStore({
	// store configs
	url: baseURL + '/stock/combos/marca',
	// reader configs
	baseParams: {
		'p[limit]': 'all'
	},
	root: 'records',
	autoLoad:true,
	idProperty: 'stock_marca_id',
	fields: ['stock_marca_id','marca']
});

var stockImpuestoStore = new Ext.data.ArrayStore({
	idIndex: 0,  
    fields: ['id','valor'],
    data: [
    	[0,'Exento'],
    	[5,'5%'],
    	[10,'10%']
    ]
});


var stockEstadoStore = new Ext.data.ArrayStore({
	idIndex: 0,  
    fields: ['id','valor'],
    data: [
    	['A','Activo'],
    	['I','Inactivo'],
    	['D','Descontinuado'],
    	['O','Obsoleto'],
    ]
});


var stockGarantiaTipoStore = new Ext.data.JsonStore({
	// store configs
	url: baseURL + '/stock/combos/garantia-tipo',
	// reader configs
	root: 'records',
	baseParams: {
		'p[limit]': 'all'
	},
	autoLoad:true,
	idProperty: 'stock_garantia_tipo_id',
	fields: ['stock_garantia_tipo_id','garantia_tipo']
});


viewContainer.bodyPanel = [{
	layout: 'fit',
	xtype: 'container',
	autoHeight: true,
	cls: 'fittedContainer',
	items: [
			{
				xtype: 'container',
				autoHeight: true,
				id: 'secondMainContainer',
				layout: 'column',
				items:[
						{
							xtype: 'container',
							columnWidth: .65,
							layout: 'anchor',
							items:[
									{
										xtype: 'container',
										html: 'Mantener Articulo',
										cls: 'mainTitle'
									},
									{
				       	       			xtype: 'container',
				       	       			itemId: 'gridContainer',
				       	       			cls: 'gridContainer',
				       	       			layout: 'anchor',
				       	       			items: [
				       	       			        {
					       	       			        xtype: 'toolbar',
					       	       			        style:{padding:'5px'},
					       	       			        items:[
					       	       			               {
						       	       			               xtype: 'displayfield',
						       	       			               style:{margin: '0 5px'},
						       	       			         	   value: 'Nombre: '
					       	       			               },
					       	       			               {
						       	       			               xtype: 'textfield',
						       	       			               name: 'articulo',
						       	       			               width: 75
					       	       			               },
					       	       			               {
						       	       			               xtype: 'displayfield',
						       	       			               style:{margin: '0 5px'},
						       	       			         	   value: 'Codigo: '
					       	       			               },
					       	       			               {
						       	       			               xtype: 'textfield',
						       	       			               name: 'codigo',
						       	       			               width: 75
					       	       			               },
					       	       			               {
						       	       			               xtype: 'displayfield',
						       	       			               style:{margin: '0 5px'},
						       	       			         	   value: 'Marca: '
					       	       			               },
					       	       			               {
						       	       			               xtype: 'combo',
						       	       			               store: stockMarcaStore,
						       	       			               displayField: 'marca',
						       	       			               triggerAction: 'all',
						       	       			               valueField: 'stock_marca_id',
						       	       			               name: 'marca',
						       	       			               width: 115
					       	       			               },
					       	       			               {
						       	       			               xtype: 'displayfield',
						       	       			               style:{margin: '0 5px'},
						       	       			         	   value: 'Categoria: '
					       	       			               },
					       	       			               {
						       	       			               xtype: 'combo',
						       	       			               store: stockCategoriaStore,
						       	       			               displayField: 'categoria',
						       	       			               triggerAction: 'all',
						       	       			               valueField: 'stock_categoria_id',
						       	       			               name: 'categoria',
						       	       			               width: 115
					       	       			               },'->',
					       	       			         		{
						       	       			               xtype: 'button',
						       	       			         	   iconCls: 'addIcon',
						       	       			               text: 'Buscar',
						       	       			               handler: function(b,e){
																    var padre = b.ownerCt;
																    //obtener valor del campo de texto
																    var campo = padre.find('name','articulo');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    mainStore.setBaseParam('s[articulo]',campo.getValue());
																    }
																    
																    campo = padre.find('name','codigo');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    mainStore.setBaseParam('s[codigo]',campo.getValue());
																    }
																    
																    campo = padre.find('name','marca');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    mainStore.setBaseParam('s[marca]',campo.getValue());
																    }
																    
																    campo = padre.find('name','categoria');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    mainStore.setBaseParam('s[categoria]',campo.getValue());
																    }
																    
																    mainStore.load();
								       	       			       }
					       	       			               },
					       	       			         		{
						       	       			               xtype: 'button',
						       	       			         	   iconCls: 'addIcon',
						       	       			               text: 'Limpiar',
						       	       			               handler: function(b,e){
																    var padre = b.ownerCt;
																    //obtener valor del campo de texto
																    var campo = padre.find('name','articulo');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    campo.setValue(null);
																	    mainStore.setBaseParam('s[articulo]',null);
																	    
																    }
																    
																    campo = padre.find('name','codigo');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    campo.setValue(null);
																	    mainStore.setBaseParam('s[codigo]',null);
																    }
																    
																    campo = padre.find('name','marca');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    campo.setValue(null);
																	    mainStore.setBaseParam('s[marca]',null);
																    }
																    
																    campo = padre.find('name','categoria');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    campo.setValue(null);
																	    mainStore.setBaseParam('s[categoria]',null);
																    }
																    
																    mainStore.load();
								       	       			       }
					       	       			               }
							       	       			]
				       	       			        },
				       	       					{
				               						xtype: 'grid',
				               						height: 300,
				               						id: 'mainGrid',
				               						stripeRows: true,
				               						loadMask: true,
				               						sm: new Ext.grid.CellSelectionModel(),
				               						viewConfig: {
				               					        forceFit: true,
				               					        emptyText: 'Sin Registros',
				               					        loadingText: 'Cargando .. '
				               						},
				               						store: mainStore,
				               						cm: new Ext.grid.ColumnModel([
				               							{ header: "Categ.", dataIndex: 'categoria',  width: 100},
				               							{ header: "Marca", dataIndex: 'marca',  width: 100},
														{ header: "Nombre", dataIndex: 'nombre', width: 160},
														{ header: "Codigo", dataIndex: 'codigo',  width: 100},
														{ header: "Precio", dataIndex: 'precio_venta',  width: 60, renderer: function(v,meta,record){
															return v + ' ' + record.data.simbolo;
														}},
														{ header: "Existencia", dataIndex: 'existencia',  width: 60},
														{ header: "Ver", dataIndex: null,  width: 32, align: 'center', renderer: function(v,meta,record){
															return '<div class="viewIcon" onclick="verArticulo(' + record.data.stock_articulo_id + ')"></div>';
														}},
														{ header: "Editar", dataIndex: null,  width: 32, align: 'center', renderer: function(v,meta,record){
															return '<div class="editIcon" onclick="editarArticulo(' + record.data.stock_articulo_id + ')"></div>';
														}},
														{ header: "Borrar", dataIndex: null,  width: 32, align: 'center', renderer: function(v,meta,record){
															return '<div class="deleteIcon" onclick="borrarArticulo(' + record.data.stock_articulo_id + ')"></div>';
														}}
														])
				           						}
				       	       			]
				       	   			},
				       	   			{
				       	       			xtype: 'toolbar',
				       	       			layout: 'toolbar',
				       	       			cls: 'pagingContainer',
				       	       			items:[
				       	       			        {
					       	       			        xtype: 'button',
					       	       			        iconCls: 'addIcon',
					       	       			        text: 'Agregar',
													handler: function(b,e){
														//buscamos destino
														var destino = Ext.getCmp('formContainer');
														if(destino)
														{
															destino.removeAll();
															var addedEl = destino.add(formularioStockArticulo(true, null, false, false));
															destino.doLayout();
															addedEl.body.highlight();
														}
													}
				       	       			        },
						       	       			'->',
				       	       	   				{
				       	       	       				xtype: 'paging',
				       	       	       				displayInfo: true,
				       	       	       				store: mainStore,
				       	       	       				pageSize: 10,
				       	       	       				preprendButtons: true
				       	       	   				}
				       	       			]
				       	   			}
							]
						},
						{
							xtype: 'container',
							columnWidth: .35,
							layout: 'anchor',
							items:[
			    					{
			    						xtype: 'container',
			    						layout: 'anchor',
			    						cls: 'oculto',
			    						id: 'messageBox',
			    						items:[
			    						       {
			        						       xtype: 'container',
			    						    	   html: 'Generico'
			    						       }
			    					
			   	    					]
			    					},
							       {
									     xtype: 'container',
									     layout: 'anchor',
									     id: 'formContainer'
							       }
									/*{
										xtype: 'panel',
										title: 'Crear Org',
										cls: 'ladoDerecho',
										layout: 'anchor',
										height: 200,
										items:[]
									}*/
							]
						}
				]
			}
	]
},
{
	xtype: 'container',
	columnWidth: 1,
	layout: 'column',
	cls: 'quickAccessBottom',
	items:[
			{
				xtype: 'button',
				text: 'Agregar Marca'
			}			
	]
}];
</script>