<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>Sistema de Gestion</title>
        <link rel="stylesheet" href="<?=$this->basePath();?>/extjs/resources/css/ext-all.css"/>
        <style type="text/css">
        	body{
        		overflow-x: hidden !important;
        	}
        </style>
		<script type="text/javascript" src="<?php echo $this->basePath(); ?>/extjs/adapter/ext/ext-base.js"></script>
		<script type="text/javascript" src="<?php echo $this->basePath(); ?>/extjs/ext-all.js"></script>
		<script type="text/javascript" src="<?=$this->basePath()?>/extjs/src/locale/ext-lang-es.js">  </script> 
		<?php
			$texto = "";

			if ($this->messages){
				$texto .= '<ul>';
				foreach($this->messages as $message)	
				{
					$texto .= ('<li>'.$message.'</li>');	
				}	
				$texto .= '</ul>';
			}
		?>		
		<script type="text/javascript">
		var mensajes = '<?php echo $texto; ?>';
		
		var baseURL = '<?=$this->basePath()?>';

		
			Ext.onReady(function(){
			
				new Ext.Viewport({
    				layout: 'anchor',
    				id: 'mainContainer',
    				autoScroll:true,
					//style:{overflowX:'hidden', overflowY:'auto'},
    				items: [
    					{
        					height: 32,
        					xtype: 'container',
        					cls: 'topFrame',
        					border: false,
        					id: 'frameSuperiorAbajo',
        					defaults: {xtype:'container'},
        					items:[
        							//tres bloques
        							{
        								height: 30,
        								autoWidth:true,
        								xtype: 'toolbar',
        								items: [
        								        {
        								        	xtype: 'container',
        								        	style: {marginTop: '5px'},
        								        	html: 'Ingreso al Sistema'
        								        }
        								]
        							}
        					]
    					},
    					{
    						xtype: 'container',
    						layout: 'anchor',
    						id: 'mainViewContainer',
    						items: [
    						        {
        						        xtype: 'container',
        						        layout:'hbox',
        						        layoutConfig: {
        						            align : 'middle',
        						        },
        						        items:[
        						               {
            						               xtype: 'container',
            						               flex: 1
        						               },
        						               {
            						               xtype: 'panel',
            						               height: 200,
            						               width: 400,
            						               style: {padding: '20px'},
            						               title: 'Credenciales',
            						               layout:'vbox',
	                   						        layoutConfig: {
	                   						            align : 'stretch',
	                   						        },
            						               items:[
            						                      {
                						                      xtype: 'form',
                						                      standardSubmit: true,
                						                      url: baseURL + '/login/try',
                						                      style: {padding: '10px'},
                						                      border: false,
                						                      frame: false,
                						                      items:[
                						                             {
                    						                             xtype: 'displayfield',
                    						                             hideLabel: true,
                    						                             style: {color: 'red', margin: '5px'},
                    						                             value: mensajes
                						                             },
                						                             {
                    						                             xtype: 'textfield',
                    						                             allowBlank: false,
                    						                             name: 'Credenciales[cedula]',
                    						                             fieldLabel: 'Usuario'
                						                             },
                						                             {
                    						                             xtype: 'textfield',
                    						                             allowBlank: false,
                    						                             inputType: 'password',
                    						                             name: 'Credenciales[contrasenha]',
                    						                             fieldLabel: 'Contrase&ntilde;a'
                						                             },
                						                             {
                    						                             xtype: 'hidden',
                    						                             name: 'Credenciales[orgDocumentoTipoCodigo]',
                    						                             value: null
                						                             },
                						                             {
                    						                             xtype: 'hidden',
                    						                             name: 'Credenciales[DirPaisId]',
                    						                             value: null
                						                             },
                						                             {
                    						                             xtype: 'button',
                    						                             text: 'Ingresar',
                    						                             handler: function(b,e)
                    						                             {
                    						                            	 var fp = this.ownerCt;
                    						                                 form = fp.getForm();
                    						                             	 if (!form.isValid()) {
                        						                             	 Ext.Msg.alert('Error','Hay campos inv&aacute;lidos');
                        						                             	 return;
                    						                             	 }

                    						                             	 form.submit();
                    						                             }
                						                             }
                          						              ]
            						                      }
                      						       ]
        						               },
        						               {
            						               xtype: 'container',
            						               flex: 1
        						               }
                  						]
    						        }
    	    				]
    					}
    				]
				});
	
				
			});//onready
		
		</script>
    </head>
    <body id='bodyHTML'>
    </body>
</html>
