<!-- primero stores siempre -->
<script type="text/javascript" src="<?=$this->basePath();?>/js/stores/genericoProductoStore.js"></script>
<script type="text/javascript" src="<?=$this->basePath();?>/js/stores/genericoSiNoStore.js"></script>
<script type="text/javascript" src="<?=$this->basePath();?>/js/stores/stockImpuestoStore.js"></script>
<script type="text/javascript" src="<?=$this->basePath();?>/js/stores/stockCategoriaStore.js"></script>
<script type="text/javascript" src="<?=$this->basePath();?>/js/stores/stockMarcaStore.js"></script>
<script type="text/javascript" src="<?=$this->basePath();?>/js/stores/stockMonedaStore.js"></script>
<!-- despues lo demas -->
<script type="text/javascript" src="<?=$this->basePath();?>/js/common/ventanaModal.js"></script>
<script type="text/javascript" src="<?=$this->basePath();?>/js/forms/stockArticulo.js"></script>
<script type="text/javascript" src="<?=$this->basePath();?>/js/common/hideBloque.js"></script>
<script type="text/javascript">


verDetallesProveedor = function(b,e)
{
	//obtenemos los campos del formulario
	var formulario = Ext.getCmp('mainForm');
	if(formulario)
	{
		var basicForm = formulario.getForm();
		var valores = basicForm.getFieldValues();
		
		if(valores.org_parte_id_buscar)
		{
			Ext.Msg.alert('Aviso','En Impl.');
		}
		else
			Ext.Msg.alert('Aviso','Debe seleccionar un proveedor');
	}
};

agregarProveedor = function(b,e)
{
	//obtenemos los campos del formulario
	var formulario = Ext.getCmp('mainForm');
	if(formulario)
	{
		var basicForm = formulario.getForm();
		
		var campo = basicForm.findField('org_parte_id_buscar');
		campo.clearValue();
		
		campo = basicForm.findField('displayNombre');
		campo.setValue(null);
		
		campo = basicForm.findField('displayDocumento');
		campo.setValue(null);
		
	}
};

agregarArticuloHandler = function(b,e)
{
	var formulario = Ext.getCmp('mainForm');
	if(formulario)
	{
		var basicForm = formulario.getForm();
		
		var campo1 = basicForm.findField('stock_articulo_id_codigo');
		var campo2 = basicForm.findField('stock_articulo_id_rcap');
		//solo podemos ver si tenemos articulo seleccionado
		if(campo1)
			campo1.setValue(null);
		if(campo2)
			campo2.setValue(null);
				
			//creamos ventana modal
			//anhadimos formulario pero antes obtenemos registro
			
		ventanaModal.add(formularioStockArticulo(true, null, false, true));
		ventanaModal.doLayout();
		ventanaModal.show();
			
	}
};

verDetallesArticuloHandler = function(b,e)
{

	var formulario = Ext.getCmp('mainForm');
	if(formulario)
	{
		var basicForm = formulario.getForm();
		var valores = basicForm.getFieldValues();
		
		//solo podemos ver si tenemos articulo seleccionado
		if(valores.stock_articulo_id_codigo && valores.stock_articulo_id_rcap)
		{
			//creamos ventana modal
			//anhadimos formulario pero antes obtenemos registro
			
			Ajax.PostElement.request({
				url: baseURL + '/stock/articulo/get',
				success: function(response, opt){
					var data = Ext.decode(response.responseText);
					ventanaModal.add(formularioStockArticulo(false, data, false, true));
					ventanaModal.doLayout();
					ventanaModal.show();
				},
				params:{id: valores.stock_articulo_id_codigo}
			});		
			
		}
		else
		{
			Ext.Msg.alert('Aviso','Seleccione un articulo para poder visualizar sus detalles');
		}
	}
};


function borrarArticulo(id)
{
	var registro = mainStore.getById(id);
	
	if(registro)
	{
		var destino = Ext.getCmp('formContainer');
		if(destino)
		{
			destino.removeAll();
			//hacemos solicitud

			Ext.Msg.confirm('Eliminar','Desea eliminar el elemento ' + registro.data.nombre, function(a,b){
				if(a == 'yes')
				{
					Ajax.PostElement.request({
						url: baseURL + '/stock/articulo/delete',
						success: function(response, opt){
							mainStore.reload();
						},
						jsonData:{delete:{stock_articulo_id : id}}
					});	
				}
			});
			
		}
	}
}

var mainStore = new Ext.data.JsonStore({
	// store configs
	totalProperty: 'numResults',
	//url: baseURL + '/stock/articulo/index',
	// reader configs
	root: '',
	paramNames: {
		start: 'p[page]',
		limit: 'p[limit]'
	},
	baseParams: {
		'p[limit]': 10,
		'p[page]': 0
	},
	//autoLoad:true,
	idProperty: 'fact_compra_detalle_id',
	fields: ['fact_compra_detalle_id','fact_compra_id','stock_articulo_id','cantidad','costo_unit','nombre','impuesto']
});

var orgRolParteStore = new Ext.data.JsonStore({
	// store configs
	totalProperty: 'numResults',
	url: baseURL + '/org/roles-de-partes/index',
	// reader configs
	root: 'records',
	paramNames: {
		start: 'p[page]',
		limit: 'p[limit]'
	},
	baseParams: {
		'p[limit]': 'all',
		'p[page]': 0,
		's[org_rol_codigo]':'proveedor'
	},
	//autoLoad:true,
	idProperty: 'org_parte_rol_id',
	fields: ['org_parte_rol_id',{name:'mostrar', convert:function(v,data){
		if(data.org_parte_tipo_nombre == 'Empresa')
		{
			return data.nombre;
		}
		else if(data.org_parte_tipo_nombre == 'Persona')
		{
			return data.apellido + ', ' + data.nombre;
		}
	}},'org_rol_nombre','org_parte_tipo_nombre','org_parte_id','nombre','apellido','fechaDeNacimiento','genero']
});


var stockEstadoStore = new Ext.data.ArrayStore({
	idIndex: 0,  
    fields: ['id','valor'],
    data: [
    	['A','Activo'],
    	['I','Inactivo'],
    	['D','Descontinuado'],
    	['O','Obsoleto'],
    ]
});

var stockEstadoFacturaStore = new Ext.data.ArrayStore({
	idIndex: 0,  
    fields: ['id','valor'],
    data: [
    	['P','Pagado'],
    	['A','Anulado']
    ]
});


var stockGarantiaTipoStore = new Ext.data.JsonStore({
	// store configs
	url: baseURL + '/stock/combos/garantia-tipo',
	// reader configs
	root: 'records',
	autoLoad:true,
	idProperty: 'stock_garantia_tipo_id',
	fields: ['stock_garantia_tipo_id','garantia_tipo']
});

var stockArticuloStore = new Ext.data.JsonStore({
	// store configs
	totalProperty: 'numResults',
	url: baseURL + '/stock/articulo/index',
	// reader configs
	root: 'records',
	paramNames: {
		start: 'p[page]',
		limit: 'p[limit]'
	},
	baseParams: {
		'p[limit]': 'all',
		'p[page]': 0
	},
	idProperty: 'stock_articulo_id',
	fields: ['stock_articulo_id',{name: 'mostrar', convert:function(v,data){
		return data.nombre + ' / ' + data.codigo;
	}},'rcap','categoria','codigo','existencia','marca','nombre','precio_venta','moneda','simbolo']
});


viewContainer.bodyPanel = [{
	layout: 'fit',
	xtype: 'container',
	autoHeight: true,
	cls: 'fittedContainer',
	items: [
			{
				xtype: 'container',
				autoHeight: true,
				id: 'secondMainContainer',
				layout: 'anchor',
				items:[
						{
							xtype: 'form',
							id: 'mainForm',
							labelAlign: 'right',
							layout: 'anchor',
							items:[
									{
										xtype: 'container',
										html: 'Cargar Compra',
										cls: 'mainTitle'
									},
									{
				       	       			xtype: 'container',
				       	       			itemId: 'compraContainer',
				       	       			cls: 'compraContainer',
				       	       			style:{margin: '10px auto'},
				       	       			layout: 'column',
				       	       			width: 1024,
				       	       			defaults:{cls: 'bloqueFactura azul', xtype: 'container', columnWidth: .33, height: 75},
				       	       			items: [
				       	       					{
				       	       						layout: 'column',
				       	       						height: 35,
				       	       						cls: 'bloqueFactura crema',
				       	       						style:{paddingTop: '5px'},
				       	       						items:[
				       	       								{
				       	       									xtype: 'container',
				       	       									layout: 'form',
				       	       									labelWidth: 75,
				       	       									width: 120,
				       	       									items:[
				       	       											{
				       	       												xtype: 'textfield',
				       	       												width: 35,
				       	       												fieldLabel: 'Factura Nro.'
				       	       											}
				       	       									]
				       	       								},
				       	       								{
				       	       									xtype: 'container',
				       	       									layout: 'form',
				       	       									width: 40,
				       	       									items:[
				       	       											{
				       	       												xtype: 'textfield',
				       	       												hideLabel: true,
				       	       												width: 35
				       	       											}
				       	       									]
				       	       								},
				       	       								{
				       	       									xtype: 'container',
				       	       									layout: 'form',
				       	       									width: 120,
				       	       									items:[
				       	       											{
				       	       												xtype: 'textfield',
				       	       												hideLabel: true,
				       	       												width: 100
				       	       											}
				       	       									]
				       	       								}
				       	       						]
				       	       					},
				       	       					{
				       	       						columnWidth: .34,
				       	       						height: 35,
				       	       						style: {border:'none'},
				       	       						cls: 'bloqueFactura'
				       	       					},
				       	       					{
				       	       						cls: 'bloqueFactura',
				       	       						style: {border:'none'},
				       	       						height: 35
				       	       					},
				       	       					{
				       	       						xtype: 'container',
				       	       						layout: 'column',
				       	       						cls: '',
				       	       						autoHeight:true,
				       	       						defaults:{xtype: 'container'},
				       	       						columnWidth: .67,
				       	       						items:[
				       	       								{
				       	       									layout: 'form',
				       	       									cls: 'bloqueFactura azul',
				       	       									columnWidth: .5,
				       	       									height: 200,
				       	       									items:[
				       	       											{
				       	       												xtype: 'displayfield',
				       	       												hideLabel: true,
				       	       												cls: 'titulo',
				       	       												value: 'Datos Compra'
				       	       											},
				       	       											{
			       															fieldLabel: 'Tipo Operacion',
			        														xtype: 'textfield',
			        														value: 'Compra',
			        														disabled: true
		       															},
		       															{
			       															fieldLabel: 'Estado',
			       															hiddenName: 'cont_moneda_id',
			       															width: 90,
			       															value: 'P',
			       															valueField: 'id',
			       															displayField:'valor',
			       															xtype: 'combo',
			       															store: stockEstadoFacturaStore,
			       															typeAhead:true,
			       															mode:'local',
			       															allowBlank: false
		       															},
				       	       											{
			       															fieldLabel: 'Fecha',
			       															name: 'fecha',
			       															allowBlank: false,
			        														xtype: 'datefield',
			        														value: new Date(),
			        														listeners:{
			        															'change':function(thisEl, newValue, oldValue)
			        															{
			        																if(!newValue)
			        																	thisEl.setValue(oldValue);
			        																	
			        																var padre = thisEl.ownerCt;
			        																var f1, f2, diasDif;
			        																var valorFecha = thisEl.value.split('/');
			        																f1 = new Date(valorFecha[1] + '/' + valorFecha[0] + '/' + valorFecha[2]);
			        																
			        																
			        																var dias = padre.find('name','dias');
			        																if(dias.length>0)
			        																{
			        																	dias = dias[0];
			        																	diasDif = dias.value;
			        																}
			        																
			        																
			        																var fecha_vencimiento = padre.find('name','fecha_vencimiento');
			        																if(fecha_vencimiento.length>0)
			        																{
			        																	fecha_vencimiento = fecha_vencimiento[0];
			        																	var valorVenc = thisEl.value;
			        																	if(valorVenc)
			        																	{
			        																		valorVenc = valorVenc.split('/');
			        																		f2 = new Date(valorVenc[1] + '/' + valorVenc[0] + '/' + valorVenc[2]);	
			        																		
			        																		
			        																		f2.setDate(parseInt(f1.getDate()) + parseInt(diasDif));
			        																		
			        																		fecha_vencimiento.setValue(f2);
			        																	}
			        																}
			        															}
			        														}
		       															},
		       															{
		       																fieldLabel: 'Agregar D&iacute;as',
			        														xtype: 'numberfield',
			        														width: 75,
			        														allowBlank: false,
			        														allowNegative: false,
			        														allowDecimals: false,
			        														name: 'dias',
			        														value: 0,
			        														listeners:{
			        															'change':function(thisEl, newValue, oldValue)
			        															{
			        																if(!newValue)
			        																	thisEl.setValue(oldValue);
			        																	
			        																var f1, f2;
			        																
			        																var padre = thisEl.ownerCt;
			        																var fecha = padre.find('name','fecha');
			        																if(fecha.length>0)
			        																{
			        																	fecha = fecha[0];
			        																	var valorFecha = fecha.value;
			        																	
			        																	if(valorFecha)
			        																	{
			        																		valorFecha = valorFecha.split('/');
			        																		f1 = new Date(valorFecha[1] + '/' + valorFecha[0] + '/' + valorFecha[2]);	
			        																	}
			        																	else
			        																	{
			        																		Ext.Msg.alert('Aviso','Compra sin Fecha');
			        																		return;
			        																	}
			        																}
			        																
			        																var fecha_vencimiento = padre.find('name','fecha_vencimiento');
			        																if(fecha_vencimiento.length>0)
			        																{
			        																	fecha_vencimiento = fecha_vencimiento[0];
			        																	var valorVenc = fecha.value;
			        																	if(valorVenc)
			        																	{
			        																		valorVenc = valorVenc.split('/');
			        																		f2 = new Date(valorVenc[1] + '/' + valorVenc[0] + '/' + valorVenc[2]);	
			        																		
			        																		f2.setDate(f1.getDate() + newValue);
			        																		
			        																		fecha_vencimiento.setValue(f2);
			        																	}
			        																}
			        																
			        																
			        															}
			        														}
		       															},
		       															{
		       																fieldLabel: 'Fecha Venc.',
			        														xtype: 'datefield',
			        														disabled: true,
			        														name: 'fecha_vencimiento',
			        														listeners:{
			        															'render':function(thisEl)
			        															{
			        																var padre = thisEl.ownerCt;
			        																var fecha = padre.find('name','fecha');
			        																if(fecha.length>0)
			        																{
			        																	fecha = fecha[0];
			        																	thisEl.value = fecha.value;
			        																}
			        															}
			        														}
		       															},
				       	       											{
			       															fieldLabel: 'Moneda',
			       															hiddenName: 'cont_moneda_id',
			       															width: 90,
			       															forceSelection:true,
			       															valueField: 'cont_moneda_id',
			       															displayField:'simbolo',
			       															xtype: 'combo',
			       															store: stockMonedaStore,
			       															typeAhead:true,
			       															mode:'local',
			       															allowBlank: false
		       															}
				       	       									]
				       	       								},
				       	       								{
				       	       									columnWidth: .5,
				       	       									layout: 'form',
				       	       									cls: 'bloqueFactura azul',
				       	       									height: 200,
				       	       									items:[
				       	       											{
				       	       												xtype: 'displayfield',
				       	       												hideLabel: true,
				       	       												cls: 'titulo',
				       	       												value: 'Proveedor'
				       	       											},
				       	       											{
				       	       												xtype: 'combo',
																			fieldLabel: 'RUC / Nombre',
																			cls: 'searchIcon',
																			hideTrigger: true,
																			width: 200,
																			allowBlank: false,
																			minChars: 2,
																			cls: 'searchIcon',
																			displayField: 'mostrar',
																			valueField: 'org_parte_rol_id',
																			forceSelection: true,
																			mode: 'remote',
																			triggerAction: 'all',
																			listWidth: 350,
																			queryDelay: 1000,
																			queryParam: 's[nombre]',
																			store: orgRolParteStore,
																			hiddenName: 'org_parte_id_buscar',
																			listeners:{
																				'select':function(thisField, record, index)
																				{
																					
																					//si selecciono algo tengo que poner en los campos dependientes
																					//busco ambos campos
																					var padre = thisField.ownerCt;
																					var displayNombre = padre.find('name','displayNombre');
																					var displayDocumento = padre.find('name','displayDocumento');
																					
																					if(displayNombre.length>0)
																					{
																						displayNombre = displayNombre[0];
																						
																						displayNombre.setValue(record.data.mostrar);
																					}
																					
																					if(displayDocumento.length>0)
																					{
																						displayDocumento = displayDocumento[0];
																						
																					}
																					
																					
																				},
																				'change':function(thisField, newValue, oldValue)
																				{
																					if(!newValue)
																					{
																						var padre = thisField.ownerCt;
																						var displayNombre = padre.find('name','displayNombre');
																						var displayDocumento = padre.find('name','displayDocumento');
																					
																						if(displayNombre.length>0)
																						{
																							displayNombre = displayNombre[0];
																							displayNombre.setValue(null);
																						}
																					
																						if(displayDocumento.length>0)
																						{
																							displayDocumento = displayDocumento[0];
																							displayDocumento.setValue(null);
																						}
																					}
																				}
																			}
																			
				       	       											},
				       	       											{
				       	       												xtype: 'textfield',
				       	       												fieldLabel: 'Documento',
				       	       												name: 'displayDocumento',
				       	       												disabled: true
				       	       											},
				       	       											{
				       	       												xtype: 'textfield',
				       	       												fieldLabel: 'Nombre o Raz. Social',
				       	       												name: 'displayNombre',
				       	       												disabled: true
				       	       											},
				       	       											{
				       	       												xtype: 'container',
				       	       												layout: 'column',
				       	       												defaults:{style:{margin: '0 5px'}},
				       	       												items:[
				       	       														{
				       	       															xtype: 'button',
				       	       															handler: verDetallesProveedor,
				       	       															text: 'Ver Detalles'
				       	       														},
				       	       														{
				       	       															xtype: 'button',
				       	       															iconCls: 'addIcon',
				       	       															text: 'Agregar Proveedor',
				       	       															handler: agregarProveedor
				       	       														}
				       	       												]
				       	       											}
				       	       									]
				       	       								},
				       	       								{
				       	       									layout: 'form',
				       	       									height: 180,
				       	       									cls: 'bloqueFactura azul',
				       	       									columnWidth: 1,
				       	       									items:[
				       	       											{
				       	       												xtype: 'displayfield',
				       	       												hideLabel: true,
				       	       												cls: 'titulo',
				       	       												value: 'Articulo'
				       	       											},
				       	       											{
				       	       												xtype: 'combo',
																			fieldLabel: 'Codigo / Nombre',
																			cls: 'searchIcon',
																			hideTrigger: true,
																			width: 475,
																			allowBlank: false,
																			minChars: 2,
																			cls: 'searchIcon',
																			displayField: 'mostrar',
																			valueField: 'stock_articulo_id',
																			forceSelection: true,
																			mode: 'remote',
																			triggerAction: 'all',
																			listWidth: 500,
																			queryDelay: 1000,
																			queryParam: 's[articulo]',
																			store: stockArticuloStore,
																			hiddenName: 'stock_articulo_id_codigo',
																			listeners:{
																				'beforequery':function(objectQuery)
																				{
																					objectQuery.combo.getStore().setBaseParam('s[rcap]',null);
																				},
																				'beforeselect':function(thisCombo, record, index)
																				{
																					//reseteo el otro campo
																					var padre = thisCombo.ownerCt;
																					var otroCombo = padre.find('hiddenName','stock_articulo_id_rcap');
																					if(otroCombo.length>0)
																					{
																						otroCombo = otroCombo[0];
																						otroCombo.setValue(null);
																					}
																				},
																				'select':function(thisField, record, index)
																				{
																					//reseteo el otro campo
																					var padre = thisField.ownerCt;
																					var otroCombo = padre.find('hiddenName','stock_articulo_id_rcap');
																					if(otroCombo.length>0)
																					{
																						otroCombo = otroCombo[0];
																						otroCombo.setValue(record.data.stock_articulo_id);
																					}
																					
																					
																					var cantidad = padre.find('name','cantidad');
																					if(cantidad.length>0)
																					{
																						cantidad = cantidad[0];
																						cantidad.focus(true,true);
																					}
																				},
																				'change':function(thisField, newValue, oldValue)
																				{
																					if(!thisField.isValid())
																					{
																						thisField.focus(true,true);
																					}
																				}
																			}
																			
				       	       											},
				       	       											{
				       	       												xtype: 'combo',
																			fieldLabel: 'Cod. Ref. Prov',
																			cls: 'searchIcon',
																			hideTrigger: true,
																			width: 475,
																			allowBlank: false,
																			minChars: 2,
																			cls: 'searchIcon',
																			displayField: 'rcap',
																			valueField: 'stock_articulo_id',
																			forceSelection: true,
																			mode: 'remote',
																			triggerAction: 'all',
																			listWidth: 500,
																			queryDelay: 1000,
																			queryParam: 's[rcap]',
																			store: stockArticuloStore,
																			hiddenName: 'stock_articulo_id_rcap',
																			listeners:{
																				'beforequery':function(objectQuery)
																				{
																					objectQuery.combo.getStore().setBaseParam('s[articulo]',null);
																				},
																				'beforeselect':function(thisCombo, record, index)
																				{
																					//reseteo el otro campo
																					var padre = thisCombo.ownerCt;
																					var otroCombo = padre.find('hiddenName','stock_articulo_id_codigo');
																					if(otroCombo.length>0)
																					{
																						otroCombo = otroCombo[0];
																						otroCombo.setValue(null);
																					}
																				},
																				'select':function(thisField, record, index)
																				{
																					//reseteo el otro campo
																					var padre = thisField.ownerCt;
																					var otroCombo = padre.find('hiddenName','stock_articulo_id_codigo');
																					if(otroCombo.length>0)
																					{
																						otroCombo = otroCombo[0];
																						otroCombo.setValue(record.data.stock_articulo_id);
																					}
																					
																					var cantidad = padre.find('name','cantidad');
																					if(cantidad.length>0)
																					{
																						cantidad = cantidad[0];
																						cantidad.focus(true,true);
																					}
																					
																				},
																				'change':function(thisField, newValue, oldValue)
																				{
																					if(!thisField.isValid())
																					{
																						thisField.focus(true,true);
																					}
																				}
																			}
																			
				       	       											},
				       	       											{
				       	       												xtype: 'container',
				       	       												layout: 'column',
				       	       												items:[
				       	       														{
				       	       															xtype: 'container',
				       	       															layout: 'form',
				       	       															columnWidth: .29,
				       	       															items:[
				       	       																	{
				       	       																		xtype: 'numberfield',
				       	       																		width: 50,
				       	       																		allowBlank: false,
				       	       																		allowNegative: false,
				       	       																		allowDecimals: false,
				       	       																		name: 'cantidad',
				       	       																		fieldLabel: 'Cantidad'
				       	       																	},
				       	       																	{
				       	       																		xtype: 'numberfield',
				       	       																		width: 90,
				       	       																		allowBlank: false,
				       	       																		allowNegative: false,
				       	       																		name: 'costo_unit',
				       	       																		fieldLabel: 'Costo Unit.'
				       	       																	}
				       	       															]
				       	       														},
				       	       														{
				       	       															xtype: 'container',
				       	       															layout: 'form',
				       	       															columnWidth: .36,
				       	       															style:{marginTop:'5px'},
				       	       															items:[
				       	       																	{
				       	       																		xtype: 'displayfield',
				       	       																		hideLabel: true,
				       	       																		value: '&nbsp;'
				       	       																	},
				       	       																	{
				       	       																		xtype: 'numberfield',
				       	       																		width: 80,
				       	       																		disabled:true,
				       	       																		name: 'costo_ref',
				       	       																		fieldLabel: 'Costo Ref.'
				       	       																	},
				       	       																	{
			       																					fieldLabel: '%IVA',
			       																					hiddenName: 'porcentaje_impuesto',
			       																					disabled:true,
			       																					forceSelection: true,
			       																					xtype: 'combo',
			       																					triggerAction: 'all',
			       																					store: stockImpuestoStore,
			      																					displayField: 'valor',
			       																					valueField: 'id',
			       																					mode: 'local',
			       																					width: 75,
			       																					allowBlank: false
		       																					}
				       	       															]
				       	       														},
				       	       														{
				       	       															xtype: 'container',
				       	       															layout: 'column',
				       	       															columnWidth: .35,
				       	       															items:[
				       	       																	{
				       	       																		xtype: 'container',
				       	       																		width: 80,
				       	       																		layout: 'form',
				       	       																		defaults:{style:{margin:'3px 0'}},
				       	       																		items:[
				       	       																				{
				       	       																					xtype: 'button',
				       	       																					width: 75,
				       	       																					iconCls: '',
				       	       																					handler: verDetallesArticuloHandler,
				       	       																					text: 'Detalles'
				       	       																				},
				       	       																				{
				       	       																					xtype: 'button',
				       	       																					width: 75,
				       	       																					iconCls: '',
				       	       																					handler: function(b,e){
				       	       																						Ext.Msg.alert('Aviso','En Impl.');
				       	       																					},
				       	       																					text: 'Stock'
				       	       																				},
				       	       																				{
				       	       																					xtype: 'button',
				       	       																					width: 75,
				       	       																					iconCls: 'addIcon',
				       	       																					handler: agregarArticuloHandler,
				       	       																					text: 'Articulo'
				       	       																				}
				       	       																		]
				       	       																	},
				       	       																	{
				       	       																		xtype: 'container',
				       	       																		columnWidth: 1,
				       	       																		defaults:{style:{margin:'3px 0'}},
				       	       																		layout: 'form',
				       	       																		items:[
				       	       																				{
				       	       																					xtype: 'button',
				       	       																					iconCls: 'cart',
				       	       																					width: 75,
				       	       																					height: 70,
				       	       																					handler: function(b,e){
				       	       																						Ext.Msg.alert('Aviso','En Impl.');
				       	       																					},
				       	       																					text: 'Agregar'
				       	       																				}
				       	       																		]
				       	       																	}
				       	       															]
				       	       														}
				       	       												]
				       	       											}
				       	       									]
				       	       								}
				       	       							]
				       	       					},	
				       	       					{
				       	       						xtype: 'container',
				       	       						layout: 'anchor',
				       	       						cls: '',
				       	       						defaults:{xtype: 'container'},
				       	       						autoHeight:true,
				       	       						columnWidth: .33,
				       	       						style:{color:'white', fontWeight:'bold'},
				       	       						items:[
				       	       								{
				       	       									layout: 'form',
				       	       									labelWidth: 130,
				       	       									cls: 'bloqueFactura azulOscuro',
				       	       									height: 215,
				       	       									items:[
				       	       											{
				       	       												xtype: 'displayfield',
				       	       												value: 'Total Compra',
				       	       												style:{backgroundColor:'#00CCFF', color: 'black'},
				       	       												cls: 'titulo',
				       	       												hideLabel: true
				       	       											},
				       	       											{
				       	       												xtype: 'container',
				       	       												defaults:{xtype: 'textfield', disabled: true},
				       	       												layout: 'form',
				       	       												items:[
				       	       														{
				       	       															fieldLabel: '<span style="text-decoration:underline; ">Valor Total Trans.</span>'
				       	       														},
				       	       														{
				       	       															fieldLabel: 'Moneda'
				       	       														},
				       	       														{
				       	       															fieldLabel: 'IVA 10%'
				       	       														},
				       	       														{
				       	       															fieldLabel: 'IVA 5%'
				       	       														},
				       	       														{
				       	       															fieldLabel: 'IVA Exenta'
				       	       														},
				       	       														{
				       	       															fieldLabel: 'Total IVA'
				       	       														}
				       	       												]
				       	       											}
				       	       									]
				       	       								},
				       	       								{
				       	       									layout: 'column',
				       	       									cls: '',
				       	       									height: 110,
				       	       									items:[
				       	       											{
				       	       												xtype: 'container',
				       	       												layout: 'form',
				       	       												width: 130,
				       	       												items:[
				       	       														{
				       	       															xtype: 'container',
				       	       															html: '&nbsp;'
				       	       														}
				       	       												]
				       	       											},
				       	       											{
				       	       												xtype: 'container',
				       	       												layout: 'form',
				       	       												width: 100,
				       	       												items:[
				       	       														{
					       	       			        									xtype: 'button',
					       	       			        									width: 85,
					       	       			        									style:{margin: '5px 0'},
					       	       			        									iconCls: 'addIcon',
					       	       			        									handler: function(b,e){
				       	       																Ext.Msg.alert('Aviso','En Impl.');
				       	       															},
					       	       			        									text: 'Reset'
																					},
																					{
					       	       			        									xtype: 'button',
					       	       			        									width: 85,
					       	       			        									handler: function(b,e){
				       	       																Ext.Msg.alert('Aviso','En Impl.');
				       	       															},
					       	       			        									style:{margin: '5px 0'},
					       	       			        									iconCls: 'addIcon',
					       	       			        									text: 'Cancelar'
																					}
				       	       												]
				       	       											},
				       	       											{
				       	       												xtype: 'container',
				       	       												layout: 'form',
				       	       												width: 100,
				       	       												items:[
				       	       														{
					       	       			        									xtype: 'button',
					       	       			        									height: 50,
					       	       			        									style:{margin: '5px 0'},
					       	       			        									width: 95,
					       	       			        									iconCls: 'addIcon',
					       	       			        									text: 'Guardar'
																					}
				       	       												]		
				       	       											}
				       	       									]
				       	       								}
				       	       						]
				       	       					},
				       	       					{
				               						xtype: 'grid',
				               						autoHeight: true,
				               						columnWidth: 1,
				               						id: 'mainGrid',
				               						stripeRows: true,
				               						loadMask: true,
				               						sm: new Ext.grid.CellSelectionModel(),
				               						viewConfig: {
				               					        forceFit: true,
				               					        emptyText: 'Sin Registros',
				               					        loadingText: 'Cargando .. '
				               						},
				               						store: mainStore,
				               						cm: new Ext.grid.ColumnModel([
				               							{ header: "Quitar", fixed:true, dataIndex: 'categoria',  width: 40, renderer: function(v,meta,record){
				               								return '<div class="deleteIcon"></div>';
				               							}},
				               							{ header: "Cant.", fixed: true, dataIndex: 'cant',  width: 80},
														{ header: "Descrip.", dataIndex: 'descrip', width: 160},
														{ header: "Costo Unit.", dataIndex: 'precio_unit',  width: 100},
														{ header: "Exenta", dataIndex: 'exenta',  width: 100},
														{ header: "5%", dataIndex: 'cinco',  width: 100},
														{ header: "10%", dataIndex: 'diez',  width: 100}
													])
				           						}
				       	       			]
				       	   			},
				       	   			{
				       	       			xtype: 'toolbar',
				       	       			layout: 'toolbar',
				       	       			cls: 'pagingContainer',
				       	       			items:[
				       	       			]
				       	   			}
							]
						}
						
						
						/*,
						{
							xtype: 'container',
							columnWidth: .35,
							layout: 'anchor',
							items:[
			    					{
			    						xtype: 'container',
			    						layout: 'anchor',
			    						cls: 'oculto',
			    						id: 'messageBox',
			    						items:[
			    						       {
			        						       xtype: 'container',
			    						    	   html: 'Generico'
			    						       }
			    					
			   	    					]
			    					},
							       {
									     xtype: 'container',
									     layout: 'anchor',
									     id: 'formContainer'
							       }
							]
						}*/
				]
			}
	]
}];
</script>