<script type="text/javascript">
function hideBloque()
{
	var cajaMensaje = Ext.getCmp('messageBox');
	if(cajaMensaje){
		cajaMensaje.addClass('oculto');
	}	
}

function formularioArticulo(isNew, data, readOnly)
{
	return {
		xtype: 'form',
		title: (readOnly)?('Ver Articulo'):((isNew)?('Crear Articulo'):('Editar Articulo')),
		cls: 'ladoDerecho',
		bodyCssClass: 'formularioGeneral',
		layout: 'form',
		//defaults:{(readOnly)?(xtype:'displayfield'):(xtype:'textfield')},
		autoHeight: true,
		items:[
		       {
			       xtype: 'hidden',
			       name: 'stock_articulo_id',
			       value: (isNew)?(null):(data.stock_articulo_id)
		       },
		       {
			       fieldLabel: 'Nombre',
			       name: 'nombre',
			       width: 150,
			       maxLength: 40,
			       value: (isNew)?(null):(data.nombre),
			       xtype: 'textfield',
			       disabled:readOnly,
			       allowBlank: false
		       },
		       {
			       fieldLabel: 'Codigo',
			       name: 'codigo',
			       width: 115,
			       maxLength: 40,
			       value: (isNew)?(null):(data.codigo),
			       xtype: 'textfield',
			       disabled:readOnly,
			       allowBlank: false
		       },
		       {
			       fieldLabel: 'Modelo',
			       name: 'modelo',
			       maxLength: 100,
			       width: 150,
			       value: (isNew)?(null):(data.modelo),
			       xtype: 'textfield',
			       disabled:readOnly,
			       allowBlank: false
		       },
		       {
			       	fieldLabel: 'Marca',
			        hiddenName: 'stock_marca_id',
			       	width: 130,
			       	valueField: 'stock_marca_id',
			       	displayField:'marca',
			       	value: (isNew)?(null):(data.stock_marca_id),
			       	xtype: 'combo',
			       	disabled:readOnly,
			       	store: stockMarcaStore,
			       	typeAhead:true,mode:'local',
			       	allowBlank: false
		       },
		       {
			       	fieldLabel: 'Categoria',
			        hiddenName: 'stock_categoria_id',
			       	width: 130,
			       	valueField: 'stock_categoria_id',
			       	displayField:'categoria',
			       	disabled:readOnly,
			       	value: (isNew)?(null):(data.stock_categoria_id),
			       	xtype: 'combo',
			       	store: stockCategoriaStore,
			       	typeAhead:true,mode:'local',
			       	allowBlank: false
		       },
		       {
			       fieldLabel: 'NCM',
			       name: 'ncm',
			       maxLength: 100,
			       width: 150,
			       value: (isNew)?(null):(data.ncm),
			       xtype: 'textfield',
			       disabled:readOnly
		       },
		       {
			       fieldLabel: 'Descrip.',
			       name: 'descripcion',
			       disabled:readOnly,
			       width: '80%',
			       value: (isNew)?(null):(data.descripcion),
			       xtype: 'textarea'
		       },
		       {
		           xtype: 'fieldset',
		           title: 'Precio Venta',
		           layout: 'column',
		           defaults:{xtype:'container'},
		           items:[
		           			{
		           				width: 200,
		           				layout: 'form',
		           				labelWidth: 100,
		           				items:[
		       							{
			       							fieldLabel: 'Precio Venta',
			       							name: 'precio_venta',
			       							width: 80,
			       							disabled:readOnly,
			       							value: (isNew)?(null):(data.precio_venta),
			       							xtype: 'numberfield',
			      							allowBlank: false,
			      							allowDecimals:true,
			      							allowNegative: false
		       							}
		           				]
		           			},
		           			{
		           				width: 150,
		           				layout: 'form',
		           				labelWidth: 60,
		           				items:[
		           						{
			       							hideLabel:true,
			       							hiddenName: 'cont_moneda_id',
			       							width: 90,
			       							valueField: 'cont_moneda_id',
			       							displayField:'moneda',
			       							value: (isNew)?(null):(data.cont_moneda_id),
			       							xtype: 'combo',
			       							disabled:readOnly,
			       							store: stockMonedaStore,
			       							typeAhead:true,mode:'local',
			       							allowBlank: false
		       							}
		           				]
		           			}
		           ]
		       },
		       {
		           xtype: 'fieldset',
		           title: 'Garantia',
		           layout: 'column',
		           defaults:{xtype:'container'},
		           items:[
		           			{
		           				width: 150,
		           				layout: 'form',
		           				labelWidth: 80,
		           				items:[
		           						{
			       							fieldLabel: 'Tiempo Gar.',
			       							name: 'tiempo_garantia',
			       							width: 50,
			       							value: (isNew)?(null):(data.tiempo_garantia),
			       							xtype: 'numberfield',
			       							allowBlank: false,
			       							allowNegative:false,
			       							disabled:readOnly,
			       							allowDecimals: false
		       							}
		           				]
		           			},
		           			{
		           				width: 150,
		           				layout: 'form',
		           				labelWidth: 60,
		           				items:[
		           						{
			       							hideLabel:true,
			       							hiddenName: 'stock_garantia_tipo_id',
			       							width: 90,
			       							valueField: 'stock_garantia_tipo_id',
			       							displayField:'garantia_tipo',
			       							value: (isNew)?(null):(data.stock_garantia_tipo_id),
			       							xtype: 'combo',
			       							disabled:readOnly,
			       							store: stockGarantiaTipoStore,
			       							typeAhead:true,mode:'local',
			       							allowBlank: false
		       							}
		           				]
		           			}
		           ]
		       },
		       {
			       fieldLabel: '%IVA',
			       hiddenName: 'porcentaje_impuesto',
			       value: (isNew)?(null):(data.porcentaje_impuesto),
			       xtype: 'combo',
			       triggerAction: 'all',
			       store: stockImpuestoStore,
			       displayField: 'valor',
			       disabled:readOnly,
			       valueField: 'id',
			       mode: 'local',
			       width: 100,
			       allowBlank: false
		       },
		       {
			       fieldLabel: '% Max. Desc.',
			       name: 'descuento_maximo',
			       value: (isNew)?(null):(data.descuento_maximo),
			       xtype: 'numberfield',
			       disabled:readOnly,
			       width: 45,
			       allowNegative: false,
			       allowBlank: false
		       },
		       {
			       fieldLabel: 'Estado',
			       hiddenName: 'estado',
			       value: (isNew)?(null):(data.estado),
			       xtype: 'combo',
			       store: stockEstadoStore,
			       displayField: 'valor',
			       valueField: 'id',
			       disabled:readOnly,
			       mode: 'local',
			       triggerAction: 'all',
			       width: 100,
			       allowBlank: false
		       },
		       {
			       fieldLabel: 'Es Servicio?',
			       hiddenName: 'es_servicio',
			       value: (isNew)?(null):(data.tipo),
			       xtype: 'combo',
			       store: genericoSiNoStore,
			       displayField: 'valor',
			       valueField: 'id',
			       disabled:readOnly,
			       mode: 'local',
			       triggerAction: 'all',
			       width: 75,
			       value: 'N',
			       allowBlank: false
		       },
		       {
			       xtype: 'container',
			       layout: 'column',
			       defaults:{style: {margin: '5px'}},
			       items:[
							{
							    xtype: 'button',
							    text: 'Guardar',
							    handler: function(b,e){
								       //verificar si esta todo ok
								       var mainForm = b.ownerCt.ownerCt;
								       basicForm = mainForm.getForm();
								       if(basicForm.isValid())
								       {
									       var valores = basicForm.getFieldValues();
									       
							
									       if(valores.stock_articulo_id)//si existe es edicion
									       {
									    	   Ajax.PostElement.request({
												   url: baseURL + '/stock/articulo/put',
												   success: function(response, opt){
												       mainStore.reload();
												   },
												   jsonData:{
												       'put': valores,
													   'formulario': mainForm.id
												   }
											   });
									       }
									       else
									       {
									           delete valores.stock_articulo_id;
									           
										       //sino es creacion
									    	   //si esta todo ok hacemos la solicitud
									    	   Ajax.PostElement.request({
												   url: baseURL + '/stock/articulo/post',
												   success: function(response, opt){
													   mainStore.reload();
												   },
												   jsonData:{
												       'post': valores,
													   'formulario': mainForm.id
												   }
											   });
									       }
									       
									       
									       
								       }
								       else
									   {
										   Ext.Msg.alert('Aviso','Hay campos inv&aacute;lidos');
									   }       
								   }
							},
							{
								xtype: 'button',
								text: 'Cancelar',
								handler: function(b,e){
									var mainForm = b.ownerCt.ownerCt;
							        var padre = mainForm.ownerCt;
							        padre.remove(mainForm);
								}
							}
				   ]
		       }
		],
		listeners:{
			'render':function(){
				hideBloque();
			}
		}
	};	
}

function verArticulo(id)
{
	
	//var registro = mainStore.getById(id);
	
	//if(registro)
	//{
		var destino = Ext.getCmp('formContainer');
		if(destino)
		{
			destino.removeAll();
			//hacemos solicitud

			Ajax.PostElement.request({
				url: baseURL + '/stock/articulo/get',
				success: function(response, opt){
					//mainStore.reload();
					var data = Ext.decode(response.responseText);
					var addedEl = destino.add(formularioArticulo(false, data, true));
					destino.doLayout();
					addedEl.body.highlight();
				},
				params:{id:id}
			});		
				
			
		}
	//}
}

function editarArticulo(id)
{
	
	//var registro = mainStore.getById(id);
	
	//if(registro)
	//{
		var destino = Ext.getCmp('formContainer');
		if(destino)
		{
			destino.removeAll();
			//hacemos solicitud

			Ajax.PostElement.request({
				url: baseURL + '/stock/articulo/get',
				success: function(response, opt){
					//mainStore.reload();
					var data = Ext.decode(response.responseText);
					var addedEl = destino.add(formularioArticulo(false, data, false));
					destino.doLayout();
					addedEl.body.highlight();
				},
				params:{id:id}
			});		
				
			
		}
	//}
}

function borrarArticulo(id)
{
	var registro = mainStore.getById(id);
	
	if(registro)
	{
		var destino = Ext.getCmp('formContainer');
		if(destino)
		{
			destino.removeAll();
			//hacemos solicitud

			Ext.Msg.confirm('Eliminar','Desea eliminar el elemento ' + registro.data.nombre, function(a,b){
				if(a == 'yes')
				{
					Ajax.PostElement.request({
						url: baseURL + '/stock/articulo/delete',
						success: function(response, opt){
							mainStore.reload();
						},
						jsonData:{delete:{stock_articulo_id : id}}
					});	
				}
			});
			
		}
	}
}

var mainStore = new Ext.data.JsonStore({
	// store configs
	totalProperty: 'numResults',
	//url: baseURL + '/stock/articulo/index',
	// reader configs
	root: '',
	paramNames: {
		start: 'p[page]',
		limit: 'p[limit]'
	},
	baseParams: {
		'p[limit]': 10,
		'p[page]': 0
	},
	//autoLoad:true,
	idProperty: 'stock_articulo_id',
	fields: ['stock_articulo_id','cant','descrip','precio_unit','exenta','cinco','diez'],
	data: [
		{'stock_articulo_id': 1,'cant': 5,'descrip': 'Celular Sony','precio_unit':'100000 Gs','exenta':'-','cinco':'-','diez':'500000 Gs'},
		{'stock_articulo_id': 2,'cant': 5,'descrip': 'Celular Sony','precio_unit':'100000 Gs','exenta':'-','cinco':'-','diez':'500000 Gs'},
		{'stock_articulo_id': 3,'cant': 5,'descrip': 'Celular Sony','precio_unit':'100000 Gs','exenta':'-','cinco':'-','diez':'500000 Gs'},
		{'stock_articulo_id': 4,'cant': 5,'descrip': 'Celular Sony','precio_unit':'100000 Gs','exenta':'-','cinco':'-','diez':'500000 Gs'},
		{'stock_articulo_id': 5,'cant': 5,'descrip': 'Celular Sony','precio_unit':'100000 Gs','exenta':'-','cinco':'-','diez':'500000 Gs'},
		{'stock_articulo_id': 6,'cant': 5,'descrip': 'Celular Sony','precio_unit':'100000 Gs','exenta':'-','cinco':'-','diez':'500000 Gs'}
	]
});

var stockCategoriaStore = new Ext.data.JsonStore({
	// store configs
	url: baseURL + '/stock/combos/categoria',
	// reader configs
	autoLoad:true,
	root: 'records',
	idProperty: 'stock_categoria_id',
	fields: ['stock_categoria_id','categoria']
});

var stockMarcaStore = new Ext.data.JsonStore({
	// store configs
	url: baseURL + '/stock/combos/marca',
	// reader configs
	root: 'records',
	autoLoad:true,
	idProperty: 'stock_marca_id',
	fields: ['stock_marca_id','marca']
});

var stockImpuestoStore = new Ext.data.ArrayStore({
	idIndex: 0,  
    fields: ['id','valor'],
    data: [
    	[0,'Exento'],
    	[5,'5%'],
    	[10,'10%']
    ]
});

var genericoSiNoStore = new Ext.data.ArrayStore({
	idIndex: 0,  
    fields: ['id','valor'],
    data: [
    	['N','No'],
    	['S','Si']
    ]
});

var stockEstadoStore = new Ext.data.ArrayStore({
	idIndex: 0,  
    fields: ['id','valor'],
    data: [
    	['A','Activo'],
    	['I','Inactivo'],
    	['D','Descontinuado'],
    	['O','Obsoleto'],
    ]
});

var stockMonedaStore = new Ext.data.JsonStore({
	// store configs
	url: baseURL + '/stock/combos/moneda',
	// reader configs
	root: 'records',
	autoLoad:true,
	idProperty: 'cont_moneda_id',
	fields: ['cont_moneda_id','moneda']
});

var stockGarantiaTipoStore = new Ext.data.JsonStore({
	// store configs
	url: baseURL + '/stock/combos/garantia-tipo',
	// reader configs
	root: 'records',
	autoLoad:true,
	idProperty: 'stock_garantia_tipo_id',
	fields: ['stock_garantia_tipo_id','garantia_tipo']
});


viewContainer.bodyPanel = [{
	layout: 'fit',
	xtype: 'container',
	autoHeight: true,
	cls: 'fittedContainer',
	items: [
			{
				xtype: 'container',
				autoHeight: true,
				id: 'secondMainContainer',
				layout: 'anchor',
				items:[
						{
							xtype: 'container',
							layout: 'anchor',
							items:[
									{
										xtype: 'container',
										html: 'Cargar Compra',
										cls: 'mainTitle'
									},
									{
				       	       			xtype: 'container',
				       	       			itemId: 'compraContainer',
				       	       			cls: 'compraContainer',
				       	       			style:{margin: '10px auto'},
				       	       			layout: 'column',
				       	       			width: 1024,
				       	       			defaults:{cls: 'bloqueFactura azul', xtype: 'container', columnWidth: .33, height: 75},
				       	       			items: [
				       	       					/*{
				       	       						layout: 'form',
				       	       						items:[
				       	       								{
				       	       									xtype: 'numberfield',
				       	       									fieldLabel: 'Id.',
				       	       									disabled: true,
				       	       									value: 12345678
				       	       								}
				       	       						]
				       	       					},
				       	       					{
				       	       						columnWidth: .34,
				       	       						cls: 'bloqueFactura crema'
				       	       					},
				       	       					{
				       	       						layout: 'form',
				       	       						items:[
				       	       								{
				       	       									xtype: 'displayfield',
				       	       									value: 'Agregar Nuevo'
				       	       								},
				       	       								{
				       	       									xtype: 'button',
				       	       									text: 'Cliente'
				       	       								},
				       	       								{
				       	       									xtype: 'button',
				       	       									text: 'Articulo'
				       	       								}
				       	       						]
				       	       					},*/
				       	       					{
				       	       						layout: 'form',
				       	       						height: 150,
				       	       						items:[
				       	       								{
				       	       									xtype: 'displayfield',
				       	       									hideLabel: true,
				       	       									cls: 'titulo',
				       	       									value: 'Datos Compra'
				       	       								},
				       	       								{
			       												fieldLabel: 'Tipo Operacion',
			        											xtype: 'textfield',
			        											value: 'Compra',
			        											disabled: true
		       												},
				       	       								{
			       												fieldLabel: 'Fecha',
			        											xtype: 'datefield',
			        											value: '08/07/2013'
		       												},
				       	       								{
			       												fieldLabel: 'Moneda',
			       												hiddenName: 'cont_moneda_id',
			       												width: 90,
			       												valueField: 'cont_moneda_id',
			       												displayField:'moneda',
			       												xtype: 'combo',
			       												store: stockMonedaStore,
			       												typeAhead:true,mode:'local',
			       												allowBlank: false
		       												},
		       												{
		       													fieldLabel: 'Nro. Factura',
			        											xtype: 'textfield',
			        											value: '001-002-0010994'
		       												}
				       	       						]
				       	       					},
				       	       					{
				       	       						columnWidth: .34,
				       	       						layout: 'form',
				       	       						height: 150,
				       	       						cls: 'spinner',
				       	       						items:[
				       	       						]
				       	       					},
				       	       					{
				       	       						layout: 'form',
				       	       						height: 150,
				       	       						items:[
				       	       								{
				       	       									xtype: 'displayfield',
				       	       									value: 'Accesos Rapidos',
				       	       									cls: 'titulo',
				       	       									hideLabel: true
				       	       								},
				       	       								{
				       	       									xtype: 'container',
				       	       									defaults:{style: 'margin: 5px;'},
				       	       									layout: 'column',
				       	       									items:[
				       	       											{
				       	       												xtype: 'container',
				       	       												columnWidth: 1,
				       	       												items:[
				       	       														{
				       	       															xtype: 'button',
				       	       															style: {margin: '0 auto'},
				       	       															iconCls: 'addIcon',
				       	       															text: 'Crear Articulo'
				       	       														}
				       	       												]
				       	       											},
				       	       											{
				       	       												xtype: 'container',
				       	       												columnWidth: 1,
				       	       												items:[
				       	       														{
				       	       															xtype: 'button',
				       	       															style: {margin: '0 auto'},
				       	       															iconCls: 'addIcon',
				       	       															text: 'Crear Proveedor'
				       	       														}
				       	       												]
				       	       											},
				       	       											{
				       	       												xtype: 'container',
				       	       												columnWidth: 1,
				       	       												items:[
				       	       														{
				       	       															xtype: 'button',
				       	       															style: {margin: '0 auto'},
				       	       															iconCls: 'addIcon',
				       	       															text: 'Crear Moneda'
				       	       														}
				       	       												]
				       	       											}
				       	       									]
				       	       								}
				       	       						]
				       	       					},
				       	       					{
				       	       						layout: 'form',
				       	       						height: 200,
				       	       						items:[
				       	       								{
				       	       									xtype: 'displayfield',
				       	       									hideLabel: true,
				       	       									cls: 'titulo',
				       	       									value: 'Agregar Articulo'
				       	       								},
				       	       								{
				       	       									xtype: 'textfield',
				       	       									width: 180,
				       	       									cls: 'searchIcon',
				       	       									fieldLabel: 'Codigo / Nombre',
				       	       									value: '1289212 - Galaxy Ace 2'
				       	       								},
				       	       								{
				       	       									xtype: 'textfield',
				       	       									width: 150,
				       	       									fieldLabel: 'Precio Unit.',
				       	       									value: '850000'
				       	       								},
				       	       								{
				       	       									xtype: 'textfield',
				       	       									width: 75,
				       	       									fieldLabel: 'Moneda',
				       	       									value: 'Gs.'
				       	       								},
				       	       								{
				       	       									xtype: 'textfield',
				       	       									width: 150,
				       	       									fieldLabel: 'Cantidad',
				       	       									value: '10'
				       	       								},
				       	       								{
				       	       									xtype: 'textfield',
				       	       									width: 150,
				       	       									fieldLabel: 'IVA',
				       	       									value: '10%'
				       	       								},
				       	       								{
				       	       									xtype: 'button',
				       	       									iconCls: 'cart',
				       	       									text: 'Agregar Articulo'
				       	       								}
				       	       						]
				       	       					},
				       	       					{
				       	       						columnWidth: .34,
				       	       						cls: 'bloqueFactura crema',
				       	       						layout: 'form',
				       	       						height: 150,
				       	       						items:[
				       	       								{
				       	       									xtype: 'displayfield',
				       	       									hideLabel: true,
				       	       									cls: 'titulo',
				       	       									value: 'Proveedor'
				       	       								},
				       	       								{
				       	       									xtype: 'textfield',
				       	       									width: 200,
				       	       									cls: 'searchIcon',
				       	       									fieldLabel: 'RUC / Nombre',
				       	       									value: 'Omar Esgaib / 1278321-1'
				       	       								},
				       	       								{
				       	       									xtype: 'textfield',
				       	       									fieldLabel: 'Documento',
				       	       									disabled: true,
				       	       									value: '1278321-1'
				       	       								},
				       	       								{
				       	       									xtype: 'textfield',
				       	       									fieldLabel: 'Nombre o Raz. Social',
				       	       									disabled: true,
				       	       									value: 'Omar Esgaib'
				       	       								}
				       	       						]
				       	       					},
				       	       					{
				       	       						layout: 'form',
				       	       						height: 200,
				       	       						items:[
				       	       								{
				       	       									xtype: 'displayfield',
				       	       									value: 'Total Compra',
				       	       									cls: 'titulo',
				       	       									hideLabel: true
				       	       								},
				       	       								{
				       	       									xtype: 'numberfield',
				       	       									width: 200,
				       	       									disabled: true,
				       	       									fieldLabel: 'Total Pagado',
				       	       									value: '234234232'
				       	       								},
				       	       								{
				       	       									xtype: 'textfield',
				       	       									width: 75,
				       	       									disabled: true,
				       	       									fieldLabel: 'Moneda',
				       	       									value: 'Gs'
				       	       								},
				       	       								{
				       	       									xtype: 'textfield',
				       	       									width: 75,
				       	       									disabled: true,
				       	       									fieldLabel: 'IVA 10%',
				       	       									value: '12345'
				       	       								},
				       	       								{
				       	       									xtype: 'textfield',
				       	       									width: 75,
				       	       									disabled: true,
				       	       									fieldLabel: 'IVA 5%',
				       	       									value: '0'
				       	       								},
				       	       								{
				       	       									xtype: 'textfield',
				       	       									width: 75,
				       	       									disabled: true,
				       	       									fieldLabel: 'IVA Exenta',
				       	       									value: '0'
				       	       								},
				       	       								{
				       	       									xtype: 'textfield',
				       	       									width: 75,
				       	       									disabled: true,
				       	       									fieldLabel: 'Total IVA',
				       	       									value: '12345'
				       	       								}
				       	       						]
				       	       					},
				       	       					{
				               						xtype: 'grid',
				               						autoHeight: true,
				               						columnWidth: 1,
				               						id: 'mainGrid',
				               						stripeRows: true,
				               						loadMask: true,
				               						sm: new Ext.grid.CellSelectionModel(),
				               						viewConfig: {
				               					        forceFit: true,
				               					        emptyText: 'Sin Registros',
				               					        loadingText: 'Cargando .. '
				               						},
				               						store: mainStore,
				               						cm: new Ext.grid.ColumnModel([
				               							{ header: "Quitar", fixed:true, dataIndex: 'categoria',  width: 40, renderer: function(v,meta,record){
				               								return '<div class="deleteIcon"></div>';
				               							}},
				               							{ header: "Cant.", fixed: true, dataIndex: 'cant',  width: 80},
														{ header: "Descrip.", dataIndex: 'descrip', width: 160},
														{ header: "Precio Unit.", dataIndex: 'precio_unit',  width: 100},
														{ header: "Exenta", dataIndex: 'exenta',  width: 100},
														{ header: "5%", dataIndex: 'cinco',  width: 100},
														{ header: "10%", dataIndex: 'diez',  width: 100}
													])
				           						}
				       	       			]
				       	   			},
				       	   			{
				       	       			xtype: 'toolbar',
				       	       			layout: 'toolbar',
				       	       			cls: 'pagingContainer',
				       	       			items:[
				       	       					'->',
				       	       			        {
					       	       			        xtype: 'button',
					       	       			        iconCls: 'addIcon',
					       	       			        text: 'Guardar',
													handler: function(b,e){
														//buscamos destino
														var destino = Ext.getCmp('formContainer');
														if(destino)
														{
															destino.removeAll();
															var addedEl = destino.add(formularioArticulo(true, null, false));
															destino.doLayout();
															addedEl.body.highlight();
														}
													}
				       	       			        },
				       	       			        {
					       	       			        xtype: 'button',
					       	       			        iconCls: 'addIcon',
					       	       			        text: 'Reset',
													handler: function(b,e){
														//buscamos destino
														var destino = Ext.getCmp('formContainer');
														if(destino)
														{
															destino.removeAll();
															var addedEl = destino.add(formularioArticulo(true, null, false));
															destino.doLayout();
															addedEl.body.highlight();
														}
													}
				       	       			        }
				       	       			]
				       	   			}
							]
						}
						
						
						/*,
						{
							xtype: 'container',
							columnWidth: .35,
							layout: 'anchor',
							items:[
			    					{
			    						xtype: 'container',
			    						layout: 'anchor',
			    						cls: 'oculto',
			    						id: 'messageBox',
			    						items:[
			    						       {
			        						       xtype: 'container',
			    						    	   html: 'Generico'
			    						       }
			    					
			   	    					]
			    					},
							       {
									     xtype: 'container',
									     layout: 'anchor',
									     id: 'formContainer'
							       }
							]
						}*/
				]
			}
	]
}];
</script>