
<script type="text/javascript">
function hideBloque()
{
	var cajaMensaje = Ext.getCmp('messageBox');
	if(cajaMensaje){
		cajaMensaje.addClass('oculto');
	}	
}

function formularioMoneda(isNew, data, isReadOnly)
{
	return {
		xtype: 'form',
		title: (isReadOnly)?('Ver Moneda'):((isNew)?('Crear Moneda'):('Editar Moneda')),
		cls: 'ladoDerecho',
		bodyCssClass: 'formularioGeneral',
		layout: 'form',
		autoHeight: true,
		defaults:{xtype: ((isReadOnly)?('displayfield'):('textfield'))},
		items:[
		       {
			       xtype: 'hidden',
			       name: 'cont_moneda_id',
			       value: (isNew)?(null):(data.cont_moneda_id)
		       },
		       {
			       fieldLabel: 'Nombre',
			       name: 'nombre',
			       width: 150,
			       maxLength: 40,
			       value: (isNew)?(null):(data.nombre),
			       allowBlank: false
		       },
		       {
			       fieldLabel: 'Nombre Plural',
			       name: 'nombre_plural',
			       width: 115,
			       maxLength: 40,
			       value: (isNew)?(null):(data.nombre_plural),
			       allowBlank: false
		       },
		       {
			       fieldLabel: 'Simbolo',
			       name: 'simbolo',
			       maxLength: 40,
			       width: 120,
			       value: (isNew)?(null):(data.simbolo),
			       allowBlank: false
		       },
		       {
			       fieldLabel: 'Descrip.',
			       name: 'descripcion',
			       width: '80%',
			       value: (isNew)?(null):(data.descripcion),
			       disabled: isReadOnly,
			       xtype: 'textarea'
		       },
		       {
			       fieldLabel: 'Permite Decimal?',
			       name: 'permite_decimal',
			       checked: (isNew)?(false):((data.permite_decimal == 'S')?(true):(false)),
			       disabled: isReadOnly,
			       xtype: 'checkbox',
			       listeners:{
						'check':function(thisCheckBox, checked)
						{
							var padre = thisCheckBox.ownerCt;
							var campo = padre.find('name','cnt_decimales');
							if(campo.length > 0)
							{
								if(checked)
								{
									campo[0].setReadOnly(false);
									campo[0].setValue();
								}
								else
								{
									campo[0].setReadOnly(true);
									campo[0].setValue(0);
								}
							}
							
						}
				   }
		       },
		       {
			       fieldLabel: 'Cant. Decimals',
			       xtype: 'numberfield',
			       name: 'cnt_decimales',
			       width: 75,
			       allowNegative: false,
			       allowDecimals: false,
			       readOnly: (isNew)?(true):((data.permite_decimal == 'S')?(false):(true)),
			       value: (isNew)?(0):(data.cnt_decimales),
	    		   disabled: isReadOnly,
			       allowBlank: false
		       },
		       {
			       xtype: 'container',
			       layout: 'column',
			       defaults:{style: {margin: '5px'}},
			       items:[
							{
							    xtype: 'button',
							    text: 'Guardar',
							    hidden: isReadOnly,
							    handler: function(b,e){
								       //verificar si esta todo ok
								       var mainForm = b.ownerCt.ownerCt;
								       basicForm = mainForm.getForm();
								       if(basicForm.isValid())
								       {
									       var valores = basicForm.getFieldValues();
									       
									       
											if(valores.permite_decimal)
									    	   valores.permite_decimal = 'S';
									    	else
									    	   valores.permite_decimal = 'N';	
									    	   
									    	var myId = valores.cont_moneda_id;
									    	     
								
									       if(myId)//si existe es edicion
									       {
									    	   
									    	   Ajax.PostElement.request({
												   url: baseURL + '/cont/moneda/put',
												   success: function(response, opt){
												       mainStore.reload();
												   },
												   jsonData:{
												       'put': valores,
													   'formulario': mainForm.id
												   }
											   });
									       }
									       else
									       {
										       //sino es creacion
									    	   //si esta todo ok hacemos la solicitud
									    	   
									    	   delete valores.cont_moneda_id;
									    	   
									    	   Ajax.PostElement.request({
												   url: baseURL + '/cont/moneda/post',
												   success: function(response, opt){
													   mainStore.reload();
												   },
												   jsonData:{
												       'post': valores,
													   'formulario': mainForm.id
												   }
											   });
									       }
									       
									       
									       
								       }
								       else
									   {
										   Ext.Msg.alert('Aviso','Hay campos inv&aacute;lidos');
									   }       
								   }
							},
							{
								xtype: 'button',
								text: (!isReadOnly)?('Cancelar'):('Cerrar'),
								handler: function(b,e){
									var mainForm = b.ownerCt.ownerCt;
							        var padre = mainForm.ownerCt;
							        padre.remove(mainForm);
								}
							}
				   ]
		       }
		],
		listeners:{
			'render':function(){
				hideBloque();
			}
		}
	};	
}

function verMoneda(id)
{
	
	var registro = mainStore.getById(id);
	
	if(registro)
	{
		var destino = Ext.getCmp('formContainer');
		if(destino)
		{
			destino.removeAll();
			var addedEl = destino.add(formularioMoneda(false, registro.data, true));
			destino.doLayout();
			addedEl.body.highlight();
		}
	}
}

function borrarMoneda(id)
{
	Ext.Msg.confirm('Borrar','Desea borrar el elemento?', function(idButt){
		if(idButt == 'yes')
		{
			Ajax.PostElement.request({
				url: baseURL + '/cont/moneda/delete',
				success: function(response, opt){
					mainStore.reload();
				},
				jsonData:{
					'delete': [id]
				}
	 		});
		}
	});
}

function editarMoneda(id)
{
	
	var registro = mainStore.getById(id);
	
	if(registro)
	{
		var destino = Ext.getCmp('formContainer');
		if(destino)
		{
			destino.removeAll();
			var addedEl = destino.add(formularioMoneda(false, registro.data, false));
			destino.doLayout();
			addedEl.body.highlight();
		}
	}
}

var mainStore = new Ext.data.JsonStore({
	// store configs
	totalProperty: 'numResults',
	url: baseURL + '/cont/moneda/index',
	// reader configs
	root: 'records',
	paramNames: {
		start: 'p[page]',
		limit: 'p[limit]'
	},
	baseParams: {
		'p[limit]': 10,
		'p[page]': 0
	},
	autoLoad:true,
	idProperty: 'cont_moneda_id',
	fields: ['cont_moneda_id','nombre','nombre_plural','simbolo','descripcion','permite_decimal','cnt_decimales']
});


viewContainer.bodyPanel = [{
	layout: 'fit',
	xtype: 'container',
	autoHeight: true,
	cls: 'fittedContainer',
	items: [
			{
				xtype: 'container',
				autoHeight: true,
				id: 'secondMainContainer',
				layout: 'column',
				items:[
						{
							xtype: 'container',
							columnWidth: .65,
							layout: 'anchor',
							items:[
									{
										xtype: 'container',
										html: 'Mantener Moneda',
										cls: 'mainTitle'
									},
									{
				       	       			xtype: 'container',
				       	       			itemId: 'gridContainer',
				       	       			cls: 'gridContainer',
				       	       			layout: 'anchor',
				       	       			items: [
				       	       			        {
					       	       			        xtype: 'toolbar',
					       	       			        style:{padding:'5px'},
					       	       			        items:[
					       	       			               {
						       	       			               xtype: 'displayfield',
						       	       			               style:{margin: '0 5px'},
						       	       			         	   value: 'Nombre: '
					       	       			               },
					       	       			               {
						       	       			               xtype: 'textfield',
						       	       			               name: 'nombre',
						       	       			               width: 75
					       	       			               },'->',
					       	       			         		{
						       	       			               xtype: 'button',
						       	       			         	   iconCls: 'addIcon',
						       	       			               text: 'Buscar',
						       	       			               handler: function(b,e){
																    var padre = b.ownerCt;
																    //obtener valor del campo de texto
																    var campo = padre.find('name','nombre');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    mainStore.setBaseParam('s[nombre]',campo.getValue());
																    }
																    
																    mainStore.load();
								       	       			       }
					       	       			               },
					       	       			         		{
						       	       			               xtype: 'button',
						       	       			         	   iconCls: 'addIcon',
						       	       			               text: 'Limpiar',
						       	       			               handler: function(b,e){
																    var padre = b.ownerCt;
																    //obtener valor del campo de texto
																    var campo = padre.find('name','nombre');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    campo.setValue(null);
																	    mainStore.setBaseParam('s[nombre]',null);
																	    
																    }
																    
																    mainStore.load();
								       	       			       }
					       	       			               }
							       	       			]
				       	       			        },
				       	       					{
				               						xtype: 'grid',
				               						height: 300,
				               						id: 'mainGrid',
				               						stripeRows: true,
				               						loadMask: true,
				               						sm: new Ext.grid.CellSelectionModel(),
				               						viewConfig: {
				               					        forceFit: true,
				               					        emptyText: 'Sin Registros',
				               					        loadingText: 'Cargando .. '
				               						},
				               						store: mainStore,
				               						cm: new Ext.grid.ColumnModel([
														{ header: "Nombre", dataIndex: 'nombre', width: 120},
														{ header: "Nombre Plural", dataIndex: 'nombre_plural',  width: 150},
														{ header: "Simbolo", dataIndex: 'simbolo',  width: 65},
														{ header: "Descrip.", dataIndex: 'descripcion',  width: 150},
														{ header: "Permite Decimal?", dataIndex: 'permite_decimal',  width: 65},
														{ header: "Ver", dataIndex: null,  width: 32, align: 'center', renderer: function(v,meta,record){
															return '<div class="viewIcon" onclick="verMoneda(' + record.data.cont_moneda_id + ')"></div>';
														}},
														{ header: "Editar", dataIndex: null,  width: 32, align: 'center', renderer: function(v,meta,record){
															return '<div class="editIcon" onclick="editarMoneda(' + record.data.cont_moneda_id + ')"></div>';
														}},
														{ header: "Borrar", dataIndex: null,  width: 32, align: 'center', renderer: function(v,meta,record){
															return '<div class="deleteIcon" onclick="borrarMoneda(' + record.data.cont_moneda_id + ')"></div>';
														}}
														])
				           						}
				       	       			]
				       	   			},
				       	   			{
				       	       			xtype: 'toolbar',
				       	       			layout: 'toolbar',
				       	       			cls: 'pagingContainer',
				       	       			items:[
				       	       			        {
					       	       			        xtype: 'button',
					       	       			        iconCls: 'addIcon',
					       	       			        text: 'Agregar',
													handler: function(b,e){
														//buscamos destino
														var destino = Ext.getCmp('formContainer');
														if(destino)
														{
															destino.removeAll();
															var addedEl = destino.add(formularioMoneda(true, null, false));
															destino.doLayout();
															addedEl.body.highlight();
														}
													}
				       	       			        },
						       	       			'->',
				       	       	   				{
				       	       	       				xtype: 'paging',
				       	       	       				displayInfo: true,
				       	       	       				store: mainStore,
				       	       	       				pageSize: 10,
				       	       	       				preprendButtons: true
				       	       	   				}
				       	       			]
				       	   			}
							]
						},
						{
							xtype: 'container',
							columnWidth: .35,
							layout: 'anchor',
							items:[
			    					{
			    						xtype: 'container',
			    						layout: 'anchor',
			    						cls: 'oculto',
			    						id: 'messageBox',
			    						items:[
			    						       {
			        						       xtype: 'container',
			    						    	   html: 'Generico'
			    						       }
			    					
			   	    					]
			    					},
							       {
									     xtype: 'container',
									     layout: 'anchor',
									     id: 'formContainer'
							       }
									/*{
										xtype: 'panel',
										title: 'Crear Org',
										cls: 'ladoDerecho',
										layout: 'anchor',
										height: 200,
										items:[]
									}*/
							]
						}
				]
			}
	]
},
{
	xtype: 'container',
	columnWidth: 1,
	layout: 'column',
	cls: 'quickAccessBottom',
	items:[
			{
				cls: 'dataBottom',
				html: 'Agregar Organizacion',
				xtype: 'container'
			},
			{
				cls: 'dataBottom',
				html: 'Agregar Otra Cosa',
				xtype: 'container'
			},
			{
				cls: 'dataBottom',
				html: 'Ir Para Otro Lado',
				xtype: 'container'
			}				
	]
}];
</script>