<!-- todas las vistas tienen que tener un objeto DATA  -->
<script type="text/javascript">
/*
viewContainer.bodyPanel = [{
	layout: 'fit',
	xtype: 'container',
	autoHeight: true,
	cls: 'fittedContainer',
	items: [
			{
				xtype: 'container',
				layout: 'column',
				items:[
						{
							xtype: 'container',
							columnWidth: .65,
							layout: 'anchor',
							items:[
									{
										xtype: 'container',
										html: 'Mantener Organizacion',
										cls: 'mainTitle'
									},
									{
				       	       			xtype: 'container',
				       	       			itemId: 'gridContainer',
				       	       			cls: 'gridContainer',
				       	       			layout: 'anchor',
				       	       			items: [
				       	       					{
				               						xtype: 'grid',
				               						height: 300,
				               						sm: new Ext.grid.CellSelectionModel(),
				               						store: new Ext.data.JsonStore({
														// store configs
														storeId: 'myStore',
														// reader configs
														root: '',
														idProperty: 'name',
														fields: ['name', 'url', {name:'size', type: 'float'}, {name:'lastmod', type:'date'}]
														}),
				               						cm: new Ext.grid.ColumnModel([
														{ header: "Ticker", width: 60},
														{ header: "Company Name", width: 150, id: 'company'},
														{ header: "Market Cap.", width: 100},
														{ header: "$ Sales", width: 100},
														{ header: "Employees", width: 100, resizable: false}
														])
				           						}
				       	       			]
				       	   			},
				       	   			{
				       	       			xtype: 'container',
				       	       			layout: 'anchor',
				       	       			cls: 'pagingContainer',
				       	       			items:[
				       	       	   				{
				       	       	       				xtype: 'paging',
				       	       	       				store: null
				       	       	   				}
				       	       			]
				       	   			}
							]
						},
						{
							xtype: 'container',
							columnWidth: .35,
							layout: 'anchor',
							items:[
									{
										xtype: 'panel',
										title: 'Crear Org',
										cls: 'ladoDerecho',
										layout: 'anchor',
										height: 200,
										items:[]
									}
							]
						}
				]
			}
	]
},
{
	xtype: 'container',
	columnWidth: 1,
	layout: 'column',
	cls: 'quickAccessBottom',
	items:[
			{
				cls: 'dataBottom',
				html: 'Agregar Organizacion',
				xtype: 'container'
			},
			{
				cls: 'dataBottom',
				html: 'Agregar Otra Cosa',
				xtype: 'container'
			},
			{
				cls: 'dataBottom',
				html: 'Ir Para Otro Lado',
				xtype: 'container'
			}				
	]
}];
*/
</script>
<div style="margin: 30px auto; width: 550px; height: 550px; background-image: url('<?=$this->basePath();?>/img/layout/crop2.jpg');
	background-repeat: no-repeat; background-position: center center; position: relative;">
		<div style="position: absolute; top: 0; left: 40%;">
			<a href="<?=$this->basePath();?>/vender">
				<img alt="Vender" src="<?=$this->basePath();?>/img/icons/basket.png">
			</a>
		</div>
		<div style="position: absolute; bottom: 0; left: 40%;">
			<a href="<?=$this->basePath();?>/vender">
				<img alt="Organizacion" src="<?=$this->basePath();?>/img/icons/company.png">
			</a>
		</div>
		<div style="position: absolute; top: 40%; left: 0;">
			<a href="<?=$this->basePath();?>/vender">
				<img alt="Parte" src="<?=$this->basePath();?>/img/icons/purse.png">
			</a>
		</div>
		<div style="position: absolute; top: 40%; right: 0;">
			<a href="<?=$this->basePath();?>/org">
				<img alt="Contabilidad" src="<?=$this->basePath();?>/img/icons/money.png">
			</a>
		</div>
</div>