<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>Sistema de Gestion</title>
        <link rel="stylesheet" href="<?=$this->basePath();?>/extjs/resources/css/ext-all.css"/>
        <link rel="stylesheet" href="<?=$this->basePath();?>/css/layout/style.css"/>
        <link rel="stylesheet" href="<?=$this->basePath();?>/css/layout/menu.css"/>
        <link rel="stylesheet" href="<?=$this->basePath();?>/css/layout/grid.css"/>
        <link rel="stylesheet" href="<?=$this->basePath();?>/css/layout/contenedor.css"/>
        <link rel="stylesheet" href="<?=$this->basePath();?>/css/layout/messageBox.css"/>
        <link rel="stylesheet" href="<?=$this->basePath();?>/css/layout/compra.css"/>
		<script type="text/javascript" src="<?php echo $this->basePath(); ?>/extjs/adapter/ext/ext-base.js"></script>
		<script type="text/javascript" src="<?php echo $this->basePath(); ?>/extjs/ext-all.js"></script>
		<script type="text/javascript" src="<?=$this->basePath()?>/extjs/src/locale/ext-lang-es.js">  </script> 
		<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/menu.js"></script>
		<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/ajax.js"></script>
		<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/formatearFecha.js"></script>
		<script type="text/javascript">

		
		
		var baseURL = '<?=$this->basePath()?>';

		function buttonClick(b,e)
		{
			location.href = baseURL + '/' + b.modulo + '/' + b.codigo + '/index-ui';
		}
		
			Ext.onReady(function(){

				new Ext.Viewport({
    				layout: 'anchor',
    				id: 'mainContainer',
    				autoScroll:true,
					//style:{overflowX:'hidden', overflowY:'auto'},
    				items: [
    					{
        					height: 32,
        					xtype: 'container',
        					cls: 'topFrame',
        					border: false,
        					id: 'frameSuperiorAbajo',
        					defaults: {xtype:'container'},
        					items:[
        							//tres bloques
        							{
        								height: 30,
        								autoWidth:true,
        								xtype: 'toolbar',
        								items: [
        								        {
            								        text: 'Organizacion',
            								        split: true,
            								        menu:{
                								        defaults:{handler: buttonClick},
														items:[
														       {text: 'Mantener Empresa', codigo: 'empresas', modulo: 'org'},
														       {text: 'Mantener Persona', codigo: 'personas', modulo: 'org'},
														       {text: 'Mantener Roles', codigo: 'roles-de-partes', modulo: 'org'}
														]
                								    }
        								        },
        								        '-',
        								        {
            								        text: 'Stock',
            								        split: true,
            								        menu:{
            								        	defaults:{handler: buttonClick},
														items:[
														       {text: 'Mantener Articulo', codigo: 'articulo', modulo: 'stock'},
														       {text: 'Mantener Marca', codigo: 'marca', modulo: 'stock'},
														       {text: 'Mantener Categoria', codigo: 'categoria', modulo: 'stock'},
														       {text: 'Mantener Garantia Tipo', codigo: 'garantia-tipo', modulo: 'stock'}
														]
                								    }
        								        },'-',
        								        {
            								        text: 'Contabilidad',
            								        split: true,
            								        menu:{
            								        	defaults:{handler: buttonClick},
														items:[
														       {text: 'Mantener Moneda', codigo: 'moneda', modulo: 'cont'},
														       {text: 'Mantener Tasa Cambio', codigo: 'moneda-conversion', modulo: 'cont'}
														]
                								    }
        								        },'-',
        								        {
            								        text: 'Facturaci&oacute;n',
            								        split: true,
            								        menu:{
            								        	defaults:{handler: buttonClick},
														items:[
														       {text: 'Crear Venta', codigo: 'venta', modulo: 'fact'},
														       {text: 'Mantener Ventas', codigo: 'ventas', modulo: 'fact'},
														       {text: 'Crear Compra', codigo: 'compra', modulo: 'fact'},
														       {text: 'Mantener Compras', codigo: 'compras', modulo: 'fact'}
														]
                								    }
        								        },
        								        {
            								        text: 'Salir',
            								        handler: function(b,e){
														Ext.Msg.alert('Aviso','En Impl.');
                								    }
        								        }
        								]
        							}/*,
        							{
        								height: 84,
        								cls: 'topFrameMid',
        								items:[
        										{
        											xtype: 'container',
        											data: menuPrincipal,
										 			tpl: new Ext.XTemplate(
										 				'<ul class="menuPrimerNivel">',
														'<tpl for=".">',
																'<li id="{[this.getLinkId()]}" class="liPrimerNivel" codigo="{codigo}">{texto}',
																'</li>',
														'</tpl>',
														'</ul>',
														{
															getLinkId: function(values)
															{
																var result = Ext.id();
												        		this.addListener.defer(1, this, [result]);
												        		return result;
															},
															addListener: function(id)
															{

																Ext.get(id).on('mouseover', function(e)
																		{
																	
																			e.stopEvent();
																	
																			//el codigo donde se hizo click
																			var codigoClick = this.dom.attributes.codigo.value;
																			var valor = null;
																	
																			//tenemos que encontrar el codogp
																			for(var x=0; x<menuPrincipal.length; x++)
																			{
																				if(menuPrincipal[x].codigo == codigoClick)
																				{
																					valor = menuPrincipal[x];
																					break;
																				}
																			}
																	
																			if(valor)
																			{
																		
																				//guardamos los datos
																				var listaHija = valor;
																				listaHija.codigo = valor.codigo;
																				//encontramos destino y agregamos los datos
																				var abuelo = Ext.getCmp('frameSuperiorAbajo');
																				var buscado = abuelo.find('itemId','listaNivelDos');
																				if(buscado.length>0)
																				{
																					buscado = buscado[0];
																					buscado.tpl.overwrite(buscado.el, listaHija);
																				}
																			}
																	
																	
																		}
																	);
															}
														}
													),
        											width: 600,
        											height: 35,
        											style:{float:'right'}
        										},
        										{
        											xtype: 'container',
        											html: 'Crear Factura',
        											cls: 'crearFactura',
        											height: 30
        										}
        								]
        							},
        							{
											xtype:'container',
											height: 33,
        									cls: 'topFrameBot',
										 	columnWidth: 1,
										 	itemId: 'listaNivelDos',
										 	style:{margin: '0 10px', borderTop: '1px solid black'},
										 	tpl: new Ext.XTemplate(
										 		'<ul class="menuSegundoNivel">',
													'<tpl for="operaciones">',
														'<a href="{[this.getHref(parent,values)]}"><li class="liSegundoNivel">',
															'{nombre}',
														'</li></a>',
													'</tpl>',
												'</ul>',
												{
													getHref: function(parent,values)
													{
														return baseURL + '/' + parent.codigo + '/' + values.codigo + '/index-ui';
													}
												}
											)
        							}*/
        					]
    					},
    					{
    						xtype: 'container',
    						layout: 'anchor',
    						id: 'mainViewContainer',
    						items: viewContainer.bodyPanel
    					}
    				]
				});
	
				
				
			});//onready
		
		var viewContainer = Ext.ns('viewContainer');
		</script>
    </head>
    <body id='bodyHTML'>
       <?php echo $this->content; ?>
    </body>
</html>
