
<script type="text/javascript">
function hideBloque()
{
	var cajaMensaje = Ext.getCmp('messageBox');
	if(cajaMensaje){
		cajaMensaje.addClass('oculto');
	}	
}

function formularioEmpresa(isNew, id, data)
{
	console.log('isNew, id, data',isNew, id, data);
	//recorremos documentos para agregar campos de ese tipo
	
	var bloqueDocumentos = [];
	var tieneDoc = false;
	
	if(!isNew)
	{
		if(data.documentos.length > 0)
		{
			tieneDoc = true;
			for(var x=0; x<data.documentos.length; x++)
			{
				bloqueDocumentos.push({
					xtype: 'container',
					layout: 'form',
					items:[
					        {
						       xtype: 'hidden',
						       name: 'org_documento_id',
						       value: data.documentos[x].org_documento_id
					        },
							{
								xtype: 'textfield',
								name: 'valor',
								allowBlank: false,
								value: data.documentos[x].valor,
								fieldLabel: 'Numero'
							},
							{
								xtype: 'combo',
								forceSelection: true,
								mode: 'local',
								typeAhead: true,
								displayField: 'nombre',
								valueField: 'org_documento_tipo_codigo',
								store: orgDocumentoTipoStore,
								allowBlank: false,
								value: data.documentos[x].org_documento_tipo_codigo,
								name: 'org_documento_tipo_codigo',
								fieldLabel: 'Tipo'
							}
					]
				});
			}
		}
		else//no tiene doc
		{
			bloqueDocumentos.push({
				xtype: 'container',
				layout: 'form',
				items:[
						{
							xtype: 'textfield',
							name: 'valor',
							allowBlank: false,
							fieldLabel: 'Numero'
						},
						{
							xtype: 'combo',
							forceSelection: true,
							mode: 'local',
							typeAhead: true,
							displayField: 'nombre',
							valueField: 'org_documento_tipo_codigo',
							store: orgDocumentoTipoStore,
							allowBlank: false,
							name: 'org_documento_tipo_codigo',
							fieldLabel: 'Tipo'
						}
				]
			});
		}
	}
	else
	{
		bloqueDocumentos.push({
			xtype: 'container',
			layout: 'form',
			items:[
					{
						xtype: 'textfield',
						name: 'valor',
						allowBlank: false,
						fieldLabel: 'Numero'
					},
					{
						xtype: 'combo',
						forceSelection: true,
						mode: 'local',
						typeAhead: true,
						displayField: 'nombre',
						valueField: 'org_documento_tipo_codigo',
						store: orgDocumentoTipoStore,
						allowBlank: false,
						name: 'org_documento_tipo_codigo',
						fieldLabel: 'Tipo'
					}
			]
		});
	}
	
	return {
		xtype: 'form',
		title: (isNew)?('Crear Empresa'):('Editar Empresa'),
		cls: 'ladoDerecho',
		bodyCssClass: 'formularioGeneral',
		layout: 'form',
		autoHeight: true,
		items:[
		       {
			       xtype: 'hidden',
			       name: 'org_parte_id',
			       value: (isNew)?(null):(id)
		       },
		       {
			       fieldLabel: 'Nombre',
			       name: 'nombre',
			       value: (isNew)?(null):(data.nombre_organizacion),
			       xtype: 'textfield',
			       allowBlank: false
		       },
		       {
		           xtype: 'fieldset',
		           title: 'Documento',
		           labelWidth: 75,
		           items:bloqueDocumentos
		       },	
		       {
			       xtype: 'container',
			       layout: 'column',
			       defaults:{style: {margin: '5px'}},
			       items:[
							{
							    xtype: 'button',
							    text: 'Guardar',
							    handler: function(b,e){
								       //verificar si esta todo ok
								       var mainForm = b.ownerCt.ownerCt;
								       basicForm = mainForm.getForm();
								       if(basicForm.isValid())
								       {
									       var valores = basicForm.getFieldValues();

									       console.log(valores);
									      
							
									       if(valores.org_parte_id)//si existe es edicion
									       {
										       var datosDocumentos = {};
										       if(tieneDoc)
										       {
										    	 //si tiene doc , es edicion
										    	   datosDocumentos.editados = [
										    	       {
										    	    	   org_documento_id: valores.org_documento_id,
										    	    	   valor: valores.valor
											    	   }
												   ];
										       }
										       else
										       {
										    	 //si no tenia es agregado
										    	   datosDocumentos.agregados = [
										    	       {
										    	    	   org_documento_tipo_codigo: valores.org_documento_tipo_codigo,
										    	    	   valor: valores.valor
											    	   }
												   ];
										       }
											       
											      
											       
									    	   Ajax.PostElement.request({
												   url: baseURL + '/org/empresas/editar',
												   success: function(response, opt){
												       mainStore.reload();
												   },
												   jsonData:{
												       'put':{
														   'org_parte_id':valores.org_parte_id,
														   'nombre': valores.nombre,
														   'Documentos':datosDocumentos
													   },
													   'formulario': mainForm.id
												   }
											   });
									       }
									       else
									       {
										       //sino es creacion
									    	   //si esta todo ok hacemos la solicitud
									    	   Ajax.PostElement.request({
												   url: baseURL + '/org/empresas/crear',
												   success: function(response, opt){
													   mainStore.reload();
												   },
												   jsonData:{
												       'post':{
														   'org_parte_id':null,
														   'nombre': valores.nombre,
														   'Documentos':{'agregados':[{
																'org_documento_tipo_codigo': valores.org_documento_tipo_codigo,
																'valor': valores.valor
															}]}
													   },
													   'formulario': mainForm.id
												   }
											   });
									       }
									       
									       
									       
								       }
								       else
									   {
										   Ext.Msg.alert('Aviso','Hay campos inv&aacute;lidos');
									   }       
								   }
							},
							{
								xtype: 'button',
								text: 'Cancelar',
								handler: function(b,e){
									var mainForm = b.ownerCt.ownerCt;
							        var padre = mainForm.ownerCt;
							        padre.remove(mainForm);
								}
							}
				   ]
		       }
		],
		listeners:{
			'render':function(){
				hideBloque();
			}
		}
	};	
}

function borrarEmpresa(id)
{
	var destino = Ext.getCmp('formContainer');
	if(destino)
	{
		destino.removeAll();
	}
	
	var registro = mainStore.getById(id);
   	
   	if(registro)
   	{
       	Ext.Msg.show({
 		   title:'Borrar',
 		   msg: 'Esta seguro de querer borrar el elemento "' + registro.data.nombre_organizacion + '"?',
 		   buttons: Ext.Msg.YESNO,
 		   fn: function(a,b){
                if(a == 'yes')
                {
                	Ajax.PostElement.request({
					   url: baseURL + '/org/parte/borrar',
					   success: function(response, opt){
					       mainStore.reload();
					   },
					   jsonData:{
					       'delete':[id],
						   'formulario':null
					   }
				   });
                }
 	       },
 		   icon: Ext.MessageBox.QUESTION
 		});
   	}
}

function formularioVerEmpresa(data)
{
	return {
		xtype: 'form',
		title: 'Ver Empresa',
		cls: 'ladoDerecho',
		bodyCssClass: 'formularioGeneral',
		layout: 'form',
		autoHeight: true,
		defaults:{xtype: 'displayfield'},
		items:[
		       {
			       xtype: 'hidden',
			       name: 'org_parte_id',
			       value: data.org_parte_id
		       },
		       {
			       fieldLabel: 'Nombre',
			       name: 'nombre',
			       value: data.nombre_organizacion
		       },
		       {
		    	   fieldLabel: 'Fecha Fund.',
			       name: 'fecha',
			       value: data.fecha_nacimiento
		       },
		       {
			       xtype: 'container',
			       layout: 'column',
			       defaults:{style: {margin: '5px'}},
			       items:[
							{
								xtype: 'button',
								text: 'Cerrar Detalle',
								handler: function(b,e){
									var mainForm = b.ownerCt.ownerCt;
							        var padre = mainForm.ownerCt;
							        padre.remove(mainForm);
								}
							}
				   ]
		       }
		],
		listeners:{
			'render':function(){
				hideBloque();
			}
		}
	};
}

function verEmpresa(id)
{
	var registro = mainStore.getById(id);
   	
   	if(registro)
   	{
   		var destino = Ext.getCmp('formContainer');
		if(destino)
		{
			destino.removeAll();

			Ajax.PostElement.request({
				   url: baseURL + '/org/parte/get',
				   method: 'GET',
				   success: function(response, opt){
							var data = Ext.decode(response.responseText);
							var addedEl = destino.add(formularioVerEmpresa(data));
							destino.doLayout();
							addedEl.body.highlight();
						
				   },
				   params:{
				       'id':id,
					   'formulario':null
				   }
			   });
		}
		
   		
   	}
}

function editarEmpresa(id)
{
	
	var registro = mainStore.getById(id);
	
	if(registro)
	{
		var destino = Ext.getCmp('formContainer');
		if(destino)
		{
			destino.removeAll();
			var addedEl = destino.add(formularioEmpresa(false, id, registro.data));
			destino.doLayout();
			addedEl.body.highlight();
		}
	}
}

var mainStore = new Ext.data.JsonStore({
	// store configs
	totalProperty: 'numResults',
	url: baseURL + '/org/empresas/index',
	// reader configs
	root: 'records',
	paramNames: {
		start: 'p[page]',
		limit: 'p[limit]'
	},
	baseParams: {
		'p[limit]': 10,
		'p[page]': 0
	},
	autoLoad:true,
	idProperty: 'org_parte_id',
	fields: ['org_parte_id','documentos','Direcciones','contactos','org_parte_tipo_codigo','nombre_organizacion','fecha_nacimiento','foto','org_parte_tipo_nombre']
});

var orgDocumentoTipoStore = new Ext.data.JsonStore({
	// store configs
	url: baseURL + '/org/combos/org-documento-tipo',
	// reader configs
	autoLoad:true,
	root: 'records',
	idProperty: 'org_documento_tipo_codigo',
	fields: ['org_documento_tipo_codigo','nombre','descripcion']
});

viewContainer.bodyPanel = [{
	layout: 'fit',
	xtype: 'container',
	autoHeight: true,
	cls: 'fittedContainer',
	items: [
			{
				xtype: 'container',
				id: 'secondMainContainer',
				autoHeight: true,
				layout: 'column',
				items:[
						{
							xtype: 'container',
							columnWidth: .65,
							layout: 'anchor',
							items:[
									{
										xtype: 'container',
										html: 'Mantener Organizacion / Empresas',
										cls: 'mainTitle'
									},
									{
				       	       			xtype: 'container',
				       	       			itemId: 'gridContainer',
				       	       			cls: 'gridContainer',
				       	       			layout: 'anchor',
				       	       			items: [
				       	       			        {
					       	       			        xtype: 'toolbar',
					       	       			        style:{padding:'5px'},
					       	       			        items:[
					       	       			               {
						       	       			               xtype: 'displayfield',
						       	       			               style:{marginRight: '5px'},
						       	       			         	   value: 'Buscar: '
					       	       			               },
					       	       			               {
						       	       			               xtype: 'textfield',
						       	       			               name: 'nombre_busqueda'
					       	       			               },'->',
					       	       			         		{
						       	       			               xtype: 'button',
						       	       			         	   iconCls: 'addIcon',
						       	       			               text: 'Buscar',
						       	       			               handler: function(b,e){
																    var padre = b.ownerCt;
																    //obtener valor del campo de texto
																    var campo = padre.find('name','nombre_busqueda');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    mainStore.setBaseParam('s[nombre]',campo.getValue());
																	    mainStore.load();
																    }
								       	       			       }
					       	       			               },
					       	       			         		{
						       	       			               xtype: 'button',
						       	       			         	   iconCls: 'addIcon',
						       	       			               text: 'Limpiar',
						       	       			               handler: function(b,e){
																    var padre = b.ownerCt;
																    //obtener valor del campo de texto
																    var campo = padre.find('name','nombre_busqueda');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    campo.setValue(null);
																	    mainStore.setBaseParam('s[nombre]',null);
																	    mainStore.load();
																    }
								       	       			       }
					       	       			               }
							       	       			]
				       	       			        },
				       	       					{
				               						xtype: 'grid',
				               						height: 300,
				               						id: 'mainGrid',
				               						stripeRows: true,
				               						loadMask: true,
				               						sm: new Ext.grid.CellSelectionModel(),
				               						viewConfig: {
				               					        forceFit: true,
				               					        emptyText: 'Sin Registros',
				               					        loadingText: 'Cargando .. '
				               						},
				               						store: mainStore,
				               						cm: new Ext.grid.ColumnModel([
														{ header: "Nombre", dataIndex: 'nombre_organizacion', width: 160},
														{ header: "Documento(s)", dataIndex: 'documentos', width: 150, renderer: function(v,meta,record){
															if(v && v.length)
															{
																var texto = '';
																
																for(var x=0; x<v.length; x++)
																{
																	texto += (v[x].valor + ' / ' + v[x].org_documento_tipo_codigo + '<br>');
																}
																
																return texto;
															}
															
															return '-';
														}},
														{ header: "Tipo", dataIndex: 'org_parte_tipo_nombre',  width: 100},
														{ header: "Ver", dataIndex: null,  width: 32, align: 'center', renderer: function(v,meta,record){
															return '<div class="viewIcon" onclick="verEmpresa(' + record.data.org_parte_id + ')"></div>';
														}},
														{ header: "Editar", dataIndex: null,  width: 32, align: 'center', renderer: function(v,meta,record){
															return '<div class="editIcon" onclick="editarEmpresa(' + record.data.org_parte_id + ')"></div>';
														}},
														{ header: "Borrar", dataIndex: null,  width: 32, align: 'center', renderer: function(v,meta,record){
															return '<div class="deleteIcon" onclick="borrarEmpresa(' + record.data.org_parte_id + ')"></div>';
														}}
														])
				           						}
				       	       			]
				       	   			},
				       	   			{
				       	       			xtype: 'toolbar',
				       	       			layout: 'toolbar',
				       	       			cls: 'pagingContainer',
				       	       			items:[
				       	       			        {
					       	       			        xtype: 'button',
					       	       			        iconCls: 'addIcon',
					       	       			        text: 'Agregar',
													handler: function(b,e){
														//buscamos destino
														var destino = Ext.getCmp('formContainer');
														if(destino)
														{
															destino.removeAll();
															var addedEl = destino.add(formularioEmpresa(true, null, null));
															destino.doLayout();
															addedEl.body.highlight();
														}
													}
				       	       			        },
						       	       			'->',
				       	       	   				{
				       	       	       				xtype: 'paging',
				       	       	       				displayInfo: true,
				       	       	       				store: mainStore,
				       	       	       				pageSize: 10,
				       	       	       				preprendButtons: true
				       	       	   				}
				       	       			]
				       	   			}
							]
						},
						{
							xtype: 'container',
							columnWidth: .35,
							layout: 'anchor',
							items:[
			    					{
			    						xtype: 'container',
			    						layout: 'anchor',
			    						cls: 'oculto',
			    						id: 'messageBox',
			    						items:[
			    						       {
			        						       xtype: 'container',
			    						    	   html: 'Generico'
			    						       }
			    					
			   	    					]
			    					},
							       {
									     xtype: 'container',
									     layout: 'anchor',
									     id: 'formContainer'
							       }
									/*{
										xtype: 'panel',
										title: 'Crear Org',
										cls: 'ladoDerecho',
										layout: 'anchor',
										height: 200,
										items:[]
									}*/
							]
						}
				]
			}
	]
},
{
	xtype: 'container',
	columnWidth: 1,
	layout: 'column',
	cls: 'quickAccessBottom',
	items:[
			{
				cls: 'dataBottom',
				html: 'Agregar Organizacion',
				xtype: 'container'
			},
			{
				cls: 'dataBottom',
				html: 'Agregar Otra Cosa',
				xtype: 'container'
			},
			{
				cls: 'dataBottom',
				html: 'Ir Para Otro Lado',
				xtype: 'container'
			}				
	]
}];
</script>