
<script type="text/javascript">
function hideBloque()
{
	var cajaMensaje = Ext.getCmp('messageBox');
	if(cajaMensaje){
		cajaMensaje.addClass('oculto');
	}	
}

function formularioMonedaConversion(isNew, data, isReadOnly)
{
	return {
		xtype: 'form',
		title: (isReadOnly)?('Ver Tasa Cambio'):((isNew)?('Crear Tasa Cambio'):('Editar Tasa Cambio')),
		cls: 'ladoDerecho',
		bodyCssClass: 'formularioGeneral',
		layout: 'form',
		autoHeight: true,
		defaults:{xtype: ((isReadOnly)?('displayfield'):('textfield'))},
		items:[
		       {
			       xtype: 'hidden',
			       name: 'cont_moneda_conversion_id',
			       value: (isNew)?(null):(data.cont_moneda_conversion_id)
		       },
		       {
					xtype: 'combo',
					store: contMonedaStore,
					displayField: 'mostrar',
					fieldLabel: 'Origen',
					mode: 'local',
					typeAhead:true,
					disabled: isReadOnly,
					allowBlank: false,
					valueField: 'cont_moneda_id',
					hiddenName: 'cont_moneda_origen_id',
					value: (isNew)?(null):(data.cont_moneda_origen_id),
					width: 150
			   },
		       {
					xtype: 'combo',
					fieldLabel: 'Destino',
					mode: 'local',
					allowBlank: false,
					store: contMonedaStore,
					displayField: 'mostrar',
					typeAhead:true,
					width: 150,
					disabled: isReadOnly,
					valueField: 'cont_moneda_id',
					value: (isNew)?(null):(data.cont_moneda_destino_id),
					hiddenName: 'cont_moneda_destino_id'
			   },
		       {
			       fieldLabel: 'Factor',
			       name: 'factor',
			       width: 100,
			       value: (isNew)?(null):(data.factor),
			       disabled: isReadOnly,
			       xtype: 'numberfield',
			       allowBlank: false,
			       allowNegative: false,
			       allowDecimals: true,
			       decimalPrecision: 10
		       },
		       {
			       xtype: 'container',
			       layout: 'column',
			       defaults:{style: {margin: '5px'}},
			       items:[
							{
							    xtype: 'button',
							    text: 'Guardar',
							    hidden: isReadOnly,
							    handler: function(b,e){
								       //verificar si esta todo ok
								       var mainForm = b.ownerCt.ownerCt;
								       basicForm = mainForm.getForm();
								       if(basicForm.isValid())
								       {
									       var valores = basicForm.getFieldValues();
									       
									    	var myId = valores.cont_moneda_conversion_id;
									    	delete valores.cont_moneda_conversion_id;       
								
									       if(myId)//si existe es edicion
									       {
									    	   Ajax.PostElement.request({
												   url: baseURL + '/cont/moneda-conversion/editar',
												   success: function(response, opt){
												       mainStore.reload();
												   },
												   jsonData:{
												       'put': valores,
												       'id': myId,
													   'formulario': mainForm.id
												   }
											   });
									       }
									       else
									       {
										       //sino es creacion
									    	   //si esta todo ok hacemos la solicitud
									    	   
									    	   Ajax.PostElement.request({
												   url: baseURL + '/cont/moneda-conversion/crear',
												   success: function(response, opt){
													   mainStore.reload();
												   },
												   jsonData:{
												       'post': valores,
													   'formulario': mainForm.id
												   }
											   });
									       }
									       
									       
									       
								       }
								       else
									   {
										   Ext.Msg.alert('Aviso','Hay campos inv&aacute;lidos');
									   }       
								   }
							},
							{
								xtype: 'button',
								text: (!isReadOnly)?('Cancelar'):('Cerrar'),
								handler: function(b,e){
									var mainForm = b.ownerCt.ownerCt;
							        var padre = mainForm.ownerCt;
							        padre.remove(mainForm);
								}
							}
				   ]
		       }
		],
		listeners:{
			'render':function(){
				hideBloque();
			}
		}
	};	
}

function verMonedaConversion(id)
{
	
	var registro = mainStore.getById(id);
	
	if(registro)
	{
		var destino = Ext.getCmp('formContainer');
		if(destino)
		{
			destino.removeAll();
			var addedEl = destino.add(formularioMonedaConversion(false, registro.data, true));
			destino.doLayout();
			addedEl.body.highlight();
		}
	}
}

function borrarMonedaConversion(id)
{
	Ext.Msg.confirm('Borrar','Desea borrar el elemento?', function(idButt){
		if(idButt == 'yes')
		{
			Ajax.PostElement.request({
				url: baseURL + '/cont/moneda-conversion/borrar',
				success: function(response, opt){
					mainStore.reload();
				},
				jsonData:{
					'id': id
				}
	 		});
		}
	});
	
}

function editarMonedaConversion(id)
{
	
	var registro = mainStore.getById(id);
	
	if(registro)
	{
		var destino = Ext.getCmp('formContainer');
		if(destino)
		{
			destino.removeAll();
			var addedEl = destino.add(formularioMonedaConversion(false, registro.data, false));
			destino.doLayout();
			addedEl.body.highlight();
		}
	}
}

var mainStore = new Ext.data.JsonStore({
	// store configs
	totalProperty: 'numResults',
	url: baseURL + '/cont/moneda-conversion/index',
	// reader configs
	root: 'records',
	paramNames: {
		start: 'p[page]',
		limit: 'p[limit]'
	},
	baseParams: {
		'p[limit]': 10,
		'p[page]': 0
	},
	autoLoad:true,
	idProperty: 'cont_moneda_conversion_id',
	fields: ['cont_moneda_conversion_id','cont_moneda_origen_id','simbolo_destino','simbolo_origen','cont_moneda_destino_id','factor','moneda_origen','moneda_destino']
});

var contMonedaStore = new Ext.data.JsonStore({
	// store configs
	url: baseURL + '/cont/moneda/index',
	// reader configs
	autoLoad:true,
	root: 'records',
	baseParams:{'p[limit]': 'all'},
	idProperty: 'cont_moneda_id',
	fields: ['cont_moneda_id',{name: 'mostrar', convert:function(v,data){
		return data.nombre + ' (' + data.simbolo + ')';	
	}},'nombre','nombre_plural','simbolo','descripcion','permite_decimal']
});


viewContainer.bodyPanel = [{
	layout: 'fit',
	xtype: 'container',
	autoHeight: true,
	cls: 'fittedContainer',
	items: [
			{
				xtype: 'container',
				autoHeight: true,
				id: 'secondMainContainer',
				layout: 'column',
				items:[
						{
							xtype: 'container',
							columnWidth: .65,
							layout: 'anchor',
							items:[
									{
										xtype: 'container',
										html: 'Mantener Tasa Cambio',
										cls: 'mainTitle'
									},
									{
				       	       			xtype: 'container',
				       	       			itemId: 'gridContainer',
				       	       			cls: 'gridContainer',
				       	       			layout: 'anchor',
				       	       			items: [
				       	       			        {
					       	       			        xtype: 'toolbar',
					       	       			        style:{padding:'5px'},
					       	       			        items:[
					       	       			               {
						       	       			               xtype: 'displayfield',
						       	       			               style:{margin: '0 5px'},
						       	       			         	   value: 'Moneda: '
					       	       			               },
					       	       			               {
					xtype: 'combo',
					store: contMonedaStore,
					displayField: 'mostrar',
					mode: 'local',
					typeAhead:true,
					valueField: 'cont_moneda_id',
					hiddenName: 'moneda_id',
					width: 150
			   },'->',
					       	       			         		{
						       	       			               xtype: 'button',
						       	       			         	   iconCls: 'addIcon',
						       	       			               text: 'Buscar',
						       	       			               handler: function(b,e){
																    var padre = b.ownerCt;
																    //obtener valor del campo de texto
																    var campo = padre.find('hiddenName','moneda_id');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    mainStore.setBaseParam('s[cont_moneda_origen_id]',campo.getValue());
																    }
																    
																    mainStore.load();
								       	       			       }
					       	       			               },
					       	       			         		{
						       	       			               xtype: 'button',
						       	       			         	   iconCls: 'addIcon',
						       	       			               text: 'Limpiar',
						       	       			               handler: function(b,e){
																    var padre = b.ownerCt;
																    //obtener valor del campo de texto
																    var campo = padre.find('hiddenName','moneda_id');
																    if(campo.length>0)
																    {
																	    campo = campo[0];
																	    campo.setValue(null);
																	    mainStore.setBaseParam('s[cont_moneda_origen_id]',null);
																	    
																    }
																    
																    mainStore.load();
								       	       			       }
					       	       			               }
							       	       			]
				       	       			        },
				       	       					{
				               						xtype: 'grid',
				               						height: 300,
				               						id: 'mainGrid',
				               						stripeRows: true,
				               						loadMask: true,
				               						sm: new Ext.grid.CellSelectionModel(),
				               						viewConfig: {
				               					        forceFit: true,
				               					        emptyText: 'Sin Registros',
				               					        loadingText: 'Cargando .. '
				               						},
				               						store: mainStore,
				               						cm: new Ext.grid.ColumnModel([
														{ header: "Origen", dataIndex: 'moneda_origen', width: 120},
														{ header: "Destino", dataIndex: 'moneda_destino',  width: 120},
														{ header: "Factor (Ori * Des)", dataIndex: 'factor',  width: 120},
														{ header: "Ejemplo Ori -> Des", dataIndex: 'descripcion',  width: 150, renderer: function(v,meta,record){
															return '1 ' + record.data.simbolo_origen + ' x ' + record.data.factor + ' = ' + record.data.factor + ' ' + record.data.simbolo_destino; 
														}},
														/*{ header: "Ejemplo Des -> Ori", dataIndex: 'descripcion',  width: 150, renderer: function(v,meta,record){
															return '1 ' + record.data.simbolo_destino + ' / ' + record.data.factor + ' = ' + (1 / record.data.factor) + ' ' + record.data.simbolo_origen;
														}},*/
														{ header: "Ver", dataIndex: null,  width: 32, align: 'center', renderer: function(v,meta,record){
															return '<div class="viewIcon" onclick="verMonedaConversion(' + record.data.cont_moneda_conversion_id + ')"></div>';
														}},
														{ header: "Editar", dataIndex: null,  width: 32, align: 'center', renderer: function(v,meta,record){
															return '<div class="editIcon" onclick="editarMonedaConversion(' + record.data.cont_moneda_conversion_id + ')"></div>';
														}},
														{ header: "Borrar", dataIndex: null,  width: 32, align: 'center', renderer: function(v,meta,record){
															return '<div class="deleteIcon" onclick="borrarMonedaConversion(' + record.data.cont_moneda_conversion_id + ')"></div>';
														}}
														])
				           						}
				       	       			]
				       	   			},
				       	   			{
				       	       			xtype: 'toolbar',
				       	       			layout: 'toolbar',
				       	       			cls: 'pagingContainer',
				       	       			items:[
				       	       			        {
					       	       			        xtype: 'button',
					       	       			        iconCls: 'addIcon',
					       	       			        text: 'Agregar',
													handler: function(b,e){
														//buscamos destino
														var destino = Ext.getCmp('formContainer');
														if(destino)
														{
															destino.removeAll();
															var addedEl = destino.add(formularioMonedaConversion(true, null, false));
															destino.doLayout();
															addedEl.body.highlight();
														}
													}
				       	       			        },
						       	       			'->',
				       	       	   				{
				       	       	       				xtype: 'paging',
				       	       	       				displayInfo: true,
				       	       	       				store: mainStore,
				       	       	       				pageSize: 10,
				       	       	       				preprendButtons: true
				       	       	   				}
				       	       			]
				       	   			}
							]
						},
						{
							xtype: 'container',
							columnWidth: .35,
							layout: 'anchor',
							items:[
			    					{
			    						xtype: 'container',
			    						layout: 'anchor',
			    						cls: 'oculto',
			    						id: 'messageBox',
			    						items:[
			    						       {
			        						       xtype: 'container',
			    						    	   html: 'Generico'
			    						       }
			    					
			   	    					]
			    					},
							       {
									     xtype: 'container',
									     layout: 'anchor',
									     id: 'formContainer'
							       }
									/*{
										xtype: 'panel',
										title: 'Crear Org',
										cls: 'ladoDerecho',
										layout: 'anchor',
										height: 200,
										items:[]
									}*/
							]
						}
				]
			}
	]
},
{
	xtype: 'container',
	columnWidth: 1,
	layout: 'column',
	cls: 'quickAccessBottom',
	items:[
			{
				cls: 'dataBottom',
				html: 'Agregar Organizacion',
				xtype: 'container'
			},
			{
				cls: 'dataBottom',
				html: 'Agregar Otra Cosa',
				xtype: 'container'
			},
			{
				cls: 'dataBottom',
				html: 'Ir Para Otro Lado',
				xtype: 'container'
			}				
	]
}];
</script>